// ============================================================
//  나의 독서 데이터
//  - 이 파일이 "원본"입니다. 화면(index.html)의 "+ 책 추가" 버튼으로
//    넣은 책은 브라우저에만 저장되니, 영구 보관하려면 그 책들을
//    "내보내기"로 복사해 아래 배열에 붙여넣으세요.
//
//  ※ 아래 2026년 목록은 제목/별점/읽은 해만 확정값입니다.
//     author · genres · published · summary 는 제가 '확실히 아는 책'만
//     채웠고, 모르는 항목은 빈칸("", [], null)으로 두었습니다.
//     빈칸은 화면의 책 상세에서 '수정'하거나 이 파일에서 채우면 됩니다.
//
//  필드: title, author, genres[], published, readYear, cover(표지 URL),
//        isbn, summary, review, rating(1~5), quotes[]
// ============================================================

const BOOKS = [
  // ===== 독서앱 서재 영상(2026-07-13)에서 가져온 과거 기록 =====
  { title: "큐새의 일일", author: "큐새", genres: ["에세이"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791194755166.jpg", isbn: "9791194755166",
    summary: "“미루는 인생이 선사하는 느긋한 기쁨에 관하여”느슨해진 일상툰에 긴장감을 주는 큐새 그림 에세이", review: "", rating: 2, quotes: [] },
  { title: "나는 0원으로 강남 건물주보다 월세 많이 받는 온라인 건물주로 산다", author: "알파남(김지수)", genres: ["재테크"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791194600398.jpg", isbn: "9791194600398",
    summary: "안녕하세요, 애드센스로 5년만에 사업화까지 성공한 알고리즘을 파괴하는 남자 알파남이라고 합니다. 저는 우연한 출근길에 유튜브를 보고 공부를 시작해 지금까지 5년 간 23억 원의 순수익을 애드센스로만 벌었습니다. 그리고 이 책에서 그 모든 내용을 낱 낱이 다루려...", review: "", rating: 4, quotes: [] },
  { title: "엔비디아 젠슨 황, 생각하는 기계", author: "스티븐 위트", genres: ["경제경영", "과학기술"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788925573762.jpg", isbn: "9788925573762",
    summary: "세계가 주목하는 CEO 엔비디아 젠슨 황 경영 철학“엔비디아의 혁신이 곧 AI의 혁신이다!”1,095일 밀착 취재, 300여 명 핵심 관계자 심층 인터뷰,시가총액 1위 등극한 엔비디아 젠슨 황의 33년 경영사 최초 공개!엔비디아, 지난 몇 년간 주식 시장을 뜨...", review: "", rating: 4, quotes: [] },
  { title: "도시와 그 불확실한 벽", author: "무라카미 하루키", genres: ["소설"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788954699075.jpg", isbn: "9788954699075",
    summary: "첫 발표 이후 43년, 마음에 품어왔던 소설을 마침내 완성하다.하루키적 상상력의 모든 것이 담긴 결정적 세계!“이 작품에는 무언가 나에게 매우 중요한 요소가 포함되어 있다고,처음부터 그렇게 느껴왔다.” _무라카미 하루키 무라카미 하루키의 신작 장편소설 『도시와...", review: "", rating: 3, quotes: [] },
  { title: "나의 돈 많은 고등학교 친구", author: "송희구", genres: ["재테크"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791165347161.jpg", isbn: "9791165347161",
    summary: "30만 베스트셀러 『서울 자가에 대기업 다니는 김 부장 이야기』 시리즈의 송희구 저자가 2년 만에 세상에 내놓은 신작. 전작과 같이 소설 형태를 빌려와 독자들에게 돈과 인생, 부와 행복에 대한 메시지를 전한다. 소설이라고 해도 좋고, 자기계발서라 해도 좋다.", review: "", rating: 2, quotes: [] },
  { title: "종의 기원", author: "정유정", genres: ["소설", "스릴러"], published: 2016, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788956609959.jpg", isbn: "9788956609959",
    summary: "3년, 모두가 손꼽아 기다려온 소설 악惡은 어떻게 존재하고 점화되는가심연에서 건져 올린 인간 본성의 ‘어두운 숲’작가 정유정이 돌아왔다! 펴내는 작품마다 압도적인 서사와 폭발적인 이야기의 힘으로 많은 독자들의 뜨거운 사랑을 받아온 정유정이 전작 『28』 이후 ...", review: "", rating: 5, quotes: [] },
  { title: "7년의 밤", author: "정유정", genres: ["소설", "스릴러"], published: 2011, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788956604992.jpg", isbn: "9788956604992",
    summary: "세계문학상 수상 작가 정유정 장편소설7년의 밤 동안 아버지와 아들에게 일어난 슬프고 신비로우며 통렬한 이야기.제1회 세계청소년문학상 수상작 『내 인생의 스프링 캠프』, 제5회 세계문학상 수상작 『내 심장을 쏴라』의 작가 정유정의 장편소설.", review: "", rating: 5, quotes: [] },
  { title: "해리 포터와 비밀의 방", author: "조앤 K. 롤링", genres: ["소설", "판타지"], published: 2022, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788983929129.jpg", isbn: "9788983929129",
    summary: "화려한 디자인으로 재탄생한 사자와 뱀과 독수리와 오소리,『해리 포터와 비밀의 방』 기숙사 에디션 출간!그리핀도르, 슬리데린, 래번클로, 후플푸프 등, 호그와트 마법학교의 네 기숙사를 상징하는 색깔과 마법 동물을 활용해 화려한 디자인, 고급스러운 장정으로 재탄생...", review: "", rating: 3, quotes: [] },
  { title: "해리 포터와 아즈카반의 죄수", author: "조앤 K. 롤링", genres: ["소설", "판타지"], published: 2000, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788983920720.jpg", isbn: "9788983920720",
    summary: "99년 9월 미국 등지에서 첫선을 보인 뒤, 어린이들이 이 책을 사기 위해 학교를 무단 결석하는 일이 없도록 출판사가 학부모의 바람에 따라 그 출시 시기를 오후로 미루는 해프닝까지 벌어졌던 화제의 책. 저자인 조앤 롤링은 이 책으로 영국 최고 권위의 도서상인 ...", review: "", rating: 3, quotes: [] },
  { title: "채식주의자", author: "한강", genres: ["소설"], published: 2022, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788936434595.jpg", isbn: "9788936434595",
    summary: "인터내셔널 부커상, 산클레멘테 문학상 수상작전세계가 주목한 한강의 역작을 다시 만나다 2016년 인터내셔널 부커상을 수상하며 한국문학의 입지를 한단계 확장시킨 한강의 장편소설 『채식주의자』를 15년 만에 새로운 장정으로 선보인다.", review: "", rating: 3, quotes: [] },
  { title: "구글의 아침은 자유가 시작된다", author: "라즐로 복", genres: ["경제경영"], published: 2021, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788925579825.jpg", isbn: "9788925579825",
    summary: "“구글이 정답은 아니다.그러나 구글은 정답을 가지고 있다!”직원복지, 경영, 문화 등 거대 기업의 메가급 비책을 과감하게 공개한 책!테슬라, 핀터레스트, 우버 등 혁신적인 기업문화를 자랑하는 기업 뒤에는어김없이 구글의 원리가 있었다!테슬라에 입사를 하면 각종 ...", review: "", rating: 3, quotes: [] },
  { title: "더 인터뷰", author: "조선일보 위클리비즈 팀", genres: ["경제경영"], published: 2014, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788950955182.jpg", isbn: "9788950955182",
    summary: "통찰과 감동이 살아 있는 최고의 인생수업!《조선일보》 위클리비즈의 명품 인터뷰를 만나다『더 인터뷰THE INTERVIEW』는 세계적인 경제·경영 대가와 CEO들, 시대의 멘토 역할을 해주는 교수·작가들을 직접 만나 인터뷰하면서 그들의 내공와 삶의 전략을 전한다...", review: "", rating: 3, quotes: [] },
  { title: "여자는 허벅지", author: "다나베 세이코", genres: ["에세이"], published: 2016, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788955618242.jpg", isbn: "9788955618242",
    summary: "《조제와 물고기와 호랑이들》 《서른 넘어 함박눈》 《아주 사적인 시간》……여자의 마음을 확 사로잡는 연애소설 작가 다나베 세이코국내에 처음 소개되는 다나베 세이코의 에세이 《여자는 허벅지》“여자라는 동물을 그렇게 몰라?”남자의 예상을 빗나가는 여자의 욕망에 관...", review: "", rating: 2, quotes: [] },
  { title: "미생 1~9 완간 박스 세트", author: "윤태호", genres: ["만화"], published: null, readYear: null,
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "나쁜상사 1", author: "네온비", genres: ["만화"], published: null, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788901162188.jpg", isbn: "9788901162188",
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "넷플릭스 스타트업의 전설", author: "지나 키팅", genres: ["경제경영"], published: 2015, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791157840052.jpg", isbn: "9791157840052",
    summary: "수많은 경영서에서 혁신의 아이콘으로 주목받은 넷플릭스하지만 그들은 넷플릭스의 1%도 제대로 보여주지 못했다!여기 혁신의 아이콘으로 평가받는 회사가 있다. 미국의 우편 제도를 바꾸고, 문화를 즐기는 방식을 바꿨다. 또한 명성이나 연기력 같은 측정할 수 없는 지표...", review: "", rating: 3, quotes: [] },
  { title: "내리막 세상에서 일하는 노마드를 위한 안내서", author: "제현주", genres: ["에세이"], published: 2019, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791196587345.jpg", isbn: "9791196587345",
    summary: "흥미로운 일을 하고 싶은 마음과 월급 봉투 사이에서 매일 아슬아슬한 줄타기를 하고 있는 직장인들의 폭발적인 호응을 얻은 책 『내리막 세상에서 일하는 노마드를 위한 안내서』가 리커버 에디션으로 새롭게 출간되었다. 단기적 일자리가 장기적 계획을 무력화하고, 눈앞에...", review: "", rating: 4, quotes: [] },
  { title: "무인양품 디자인", author: "닛케이디자인", genres: ["디자인"], published: 2016, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788968570476.jpg", isbn: "9788968570476",
    summary: "상표 없는 좋은 제품, 노 디자인 전략어떻게 세계적 브랜드 됐을까?제품에는 색을 넣지 않고, 염색도 하지 않는다. 제품 어디에도 로고는 보이지 않는다. 무인양품 디자인은 극단적일 만큼 평범하다. 그러나 무인양품이 지금껏 만들어 판매하고 있는 상품 수는 7000...", review: "", rating: 3, quotes: [] },
  { title: "벙어리 삼룡이", author: "나도향", genres: ["소설", "고전"], published: null, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791198761293.jpg", isbn: "9791198761293",
    summary: "", review: "", rating: 2, quotes: [] },
  { title: "창의성을 지휘하라", author: "에드 캣멀·에이미 월러스", genres: ["경제경영"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791173470622.jpg", isbn: "9791173470622",
    summary: "“창의적이 되는 것과 위대하고 창의적인 문화를 구축하는 것은 완전히 다른 차원...", review: "", rating: 4, quotes: [] },
  { title: "와일드", author: "셰릴 스트레이드", genres: ["에세이", "여행"], published: 2024, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791169851008.jpg", isbn: "9791169851008",
    summary: "아마존 《뉴욕 타임스》 논픽션 부문 압도적 1위《뉴욕 타임스》, 《중앙일보》, 《보그》, 《보스턴 글로브》 선정 ‘올해의 책’김혜리, 주성철, 장도연 추천 영화 〈와일드〉 원작 에세이“나는 모든 것을 의심하는 사람이지만 이것 하나만은 굳게 믿었다.", review: "", rating: 4, quotes: [] },
  { title: "지방의 누명", author: "MBC 스페셜 제작진", genres: ["건강"], published: 2017, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791195977703.jpg", isbn: "9791195977703",
    summary: "“날씬하고 건강해지려면 이제, 지방을 먹자!”내 몸을 위한 식사 혁명, 저탄수화물 고지방 식이요법MBC 스페셜에 방송되며 숱한 화제를 모았던 지방의 누명이 책으로 출간됐다. 지방이 살을 찌우고 혈관에 쌓여 각종 질환을 일으킨다는 기존의 상식을 뒤집고, 지방을 ...", review: "", rating: 3, quotes: [] },
  { title: "운명과 분노", author: "로런 그로프", genres: ["소설"], published: 2017, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788954644860.jpg", isbn: "9788954644860",
    summary: "아마존 선정 올해의 책 1위(2015)버락 오바마가 뽑은 2015년 최고의 책전미도서상 최종 후보, 전미도서비평가협회상 최종 후보(2015)[워싱턴 포스트] [타임] [시애틀 타임스] [미네폴리스 스타트리뷴] [슬레이트] [라이브러리 저널] [커커스] NPR ...", review: "", rating: 3, quotes: [] },
  { title: "술 권하는 사회 외", author: "현진건", genres: ["소설", "고전"], published: null, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788973301669.jpg", isbn: "9788973301669",
    summary: "", review: "", rating: 4, quotes: [] },
  { title: "세 종교 이야기", author: "홍익희", genres: ["역사", "종교"], published: 2014, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788997132485.jpg", isbn: "9788997132485",
    summary: "유대교, 기독교, 이슬람교의 비교분석을 통해 틀림이 아닌 다름을 인정하는 평화공존의 길을 모색한다 세 종교의 가장 큰 차이점은 바로 예수에 대한 관점의 차이다. 유대교와 이슬람교는 예수를 신의 아들로 보지 않고 선지자 중의 한 사람으로 보고, 기독교는 예수를...", review: "", rating: 4, quotes: [] },
  { title: "루키 스마트", author: "리즈 와이즈먼", genres: ["경제경영"], published: 2015, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788947530026.jpg", isbn: "9788947530026",
    summary: "‘1만 시간의 법칙’에 종말을 고한다! 알지 못하는 것이 아는 것보다 가치 있을 때는 언제일까?끊임없이 변화가 일어나는 시대에 성공하려면 ‘루키의 눈’으로 세상을 봐야 한다. 처음으로 어떤 일을 시작했을 때 종종 최선의 성과를 올리게 되는 이유는 무엇일까?", review: "", rating: 3, quotes: [] },
  { title: "만약 우리가 천국에 산다면 행복할 수 있을까?", author: "토마스 힐란 에릭센", genres: ["인문"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791198999146.jpg", isbn: "9791198999146",
    summary: "노르웨이를 가장 행복한 나라로 만든 인류학자,그가 삶의 마지막 여정에서 깨달은‘고장 난 행복’을 고치는 방법- 유성호 서울대 법의학자 강력 추천- 베스트셀러 『인생의 의미』 작가인 토마스 힐란드 에릭센 사후에 출간되는 첫 책2024년 겨울, 노르웨이가 슬픔에 ...", review: "", rating: 3, quotes: [] },
  { title: "하루하루가 이별의 날", author: "프레드릭 배크만", genres: ["소설"], published: 2017, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791130613208.jpg", isbn: "9791130613208",
    summary: "『오베라는 남자』 『할머니가 미안하다고 전해달랬어요』의 감동을 잇는 프레드릭 배크만의 아름답고 꿈같은 이야기씁쓸하고도 달콤하다, 읽는 내내 마음이 무너지게 하는 배크만의 이 짧은 소설은 모든 걸 놓아버리는 과정에서도 느낄 수 있는 기쁨에 주목한다.", review: "", rating: 4, quotes: [] },
  { title: "A Haunted House", author: "버지니아 울프", genres: ["소설", "고전"], published: null, readYear: null,
    summary: "", review: "", rating: 2, quotes: [] },
  { title: "경희", author: "나혜석", genres: ["소설", "고전"], published: 2020, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788982226519.jpg", isbn: "9788982226519",
    summary: "『경희한국어 읽고 쓰기』는 이해 영역인 ‘읽기’와 표현 영역인 ‘쓰기를 연계하여 SNS, 문자, 이메일 작성부터 실용문, 설명문 등 실생활에 직접적으로 필요한 글부터 전문 분야의 글까지 읽고 쓸 수 있도록 하였다. 한국 문화를 접할 수 있는 풍부한 삽화와 사진...", review: "", rating: 3, quotes: [] },
  { title: "깨뜨려지는 홍등", author: "이효석", genres: ["소설", "고전"], published: null, readYear: null,
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "탈출기", author: "최서해", genres: ["소설", "고전"], published: 2015, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791186639030.jpg", isbn: "9791186639030",
    summary: "“지식인의 붓끝에서 나온 소설이 아니라그가 혈액과 체액으로 쓴 소설이다.” _소설가 이경혜식민시대 민중의 절대 빈곤과 분노를사실적으로 그려낸 최서해의 단편 모음 이경혜 작가가 쓴, 최서해 작품을 추억하는 추천글 수록[한국문학을 권하다", review: "", rating: 3, quotes: [] },
  { title: "여행의 기술", author: "알랭 드 보통", genres: ["에세이", "여행"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791199020504.jpg", isbn: "9791199020504",
    summary: "세계적인 베스트셀러 저자, 알랭 드 보통이 전하는 여행의 모든 것여행을 떠나기 전에 반드시 읽어야 할 단 한 권의 여행서", review: "", rating: 4, quotes: [] },
  { title: "죽여 마땅한 사람들", author: "피터 스완슨", genres: ["소설", "스릴러"], published: 2016, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791156756552.jpg", isbn: "9791156756552",
    summary: "“썩은 사과 몇 개를 신의 의도보다조금 일찍 추려낸다고 해서 달라질 게 뭔가요?당신은 세상을 위해 좋은 일을 하는 거예요.”미국에서 가장 까다로운 서평그룹 굿리즈 평점 4.01!출간 전 서평단 300명이 극찬한 스릴러!</br...", review: "", rating: 4, quotes: [] },
  { title: "이동진 독서법", author: "이동진", genres: ["에세이", "인문"], published: 2022, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791168123274.jpg", isbn: "9791168123274",
    summary: "2만 3천여 권의 책을 갖고 있는 장서가이자 책 읽기가 세상에서 가장 재미있다고 설파하는 못 말리는 애서가 이동진의 독서법을 담은 책. ‘1부 생각_ 그럼에도 불구하고, 책’에서는 이동진 작가가 책을 읽는 방법과 책을 사랑하는 방법을 이야기하고 있고, ‘2부 ...", review: "", rating: 3, quotes: [] },
  { title: "바봇", author: "정창영", genres: [], published: 2017, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788993690460.jpg", isbn: "9788993690460",
    summary: "스웨그 넘치는 본격 SF 생활문화 소설! 이 소설은 전업주부(house keeping husband)로 사는 작가 개인의 경험을 바탕으로, 인공지능(A.I.)과 안드로이드(인간형) 로봇을 소재로 소외된 삶을 사는 사회적 약자 혹은 노동자의 삶을 풍자적으로...", review: "", rating: 3, quotes: [] },
  { title: "권력의 기술", author: "제프리 페퍼", genres: ["경제경영"], published: 2011, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788935208869.jpg", isbn: "9788935208869",
    summary: "어떻게 권력을 얻을 것인가?파워 게임에서 똑똑하게 승리하는 전략과 전술인재 경영의 창시자로 불리우며 조직행동, 리더십, 인사관리 등 경영학의 핵심 영역에서 세계적 석학으로 인정받는 제프리 페퍼의 저서이다. 그는 이 책에서 왜 인간이 권력을 차지하기 위해 노력...", review: "", rating: 4, quotes: [] },
  { title: "디앤디파트먼트에서 배운다", author: "나가오카 겐메이", genres: ["디자인"], published: 2014, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788996264057.jpg", isbn: "9788996264057",
    summary: "[디앤디파트먼트에서 배운다, 사람들이 모여드는 ‘전하는 가게’ 만드는 법: 사면서 배우고, 먹으면서 배우는 가게]는 제대로 된 물건을 찾는 사람이 모여드는 가게, 올바른 물건과 생산자의 이야기를 전하는 가게 디앤디파트먼트 설립자 나가오카 겐메이가 현재의 디앤디...", review: "", rating: 4, quotes: [] },
  { title: "청춘의 독서", author: "유시민", genres: ["인문", "에세이"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788901294742.jpg", isbn: "9788901294742",
    summary: "시대와 함께한 영원한 ‘청춘의 책’유시민의 『청춘의 독서』 특별증보판 출간! “세상이 두려울 때마다 그들에게 길을 물었다” 『죄와 벌』부터 『자유론』까지, 유시민이 다시 펼쳐 든 오래된 지도", review: "", rating: 4, quotes: [] },
  { title: "네버웨어", author: "닐 게이먼", genres: ["소설", "판타지"], published: 2007, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788901072456.jpg", isbn: "9788901072456",
    summary: "런던의 젊은 증권맨 리처드는 어느 날 우연히 길가에 피를 흘리고 쓰러져 있는 소녀의 목숨을 구한 뒤로 이상한 일에 휘말린다. 이 세상에서 그의 존재가 흔적도 없이 지워져 투명인간처럼 되어버린 것이다. 집과 직장과 약혼녀를 모두 잃고 한순간 지상의 틈으로 굴러떨...", review: "", rating: 1, quotes: [] },
  { title: "나의 몫", author: "파리누쉬 사니이", genres: ["소설"], published: 2017, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791188140107.jpg", isbn: "9791188140107",
    summary: "두툼한 장편임에도 불구하고 순식간에 한 권을 다 읽어 내게 만드는 매력 있는 소설!사회, 가족, 모든 삶의 조건으로부터 억압받으며 살아온 여주인공 마수메의 반평생. 십대 때 처음으로 약사의 조수와 사랑에 빠지게 되지만 남몰래 키워온 감정과 들켜버린 연애편지는 ...", review: "", rating: 4, quotes: [] },
  { title: "나는 유독 그 사람이 힘들다", author: "배르벨 바르데츠키", genres: ["심리"], published: 2015, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788937823435.jpg", isbn: "9788937823435",
    summary: "전 세계 베스트셀러《따귀 맞은 영혼》《너는 나에게 상처를 줄 수 없다》 저자이자독일 최고의 심리상담가 배르벨 바르데츠키의 관계심리 결정판!‘일보다 사람이 힘든 당신’을 위한 심리, 행동 처방전‘일보다 사람이 힘든가?", review: "", rating: 4, quotes: [] },
  { title: "세상은 바꿀 수 있습니다", author: "이용마", genres: ["사회", "에세이"], published: 2017, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788936486211.jpg", isbn: "9788936486211",
    summary: "해직기자 이용마가두 아들에게 들려주는 삶과 꿈“언론이 질문을 못하면 민주주의가 망하는 겁니다.”2017년 10월 25일, 전국언론노동조합 MBC 본부(MBC 노조)가 주도하여 서울광장에서 개최된 파업콘서트 ‘다시 만나도 좋은 친구’에 생각지 못한 출연자가 등장...", review: "", rating: 3, quotes: [] },
  { title: "아픔이 길이 되려면", author: "김승섭", genres: ["사회"], published: 2017, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788962621952.jpg", isbn: "9788962621952",
    summary: "혐오발언, 구직자 차별, 고용불안, 참사…사회적 상처는 우리 몸을 어떻게 병들게 하는가?데이터가 말해주는 우리가 아픈 진짜 이유『아픔이 길이 되려면』은 공중보건의사 시절부터 김승섭 교수가 걸어온 치열한 고민의 흔적들과 연구의 발자취를 고스란히 담고 있다.", review: "", rating: 4, quotes: [] },
  { title: "만화로 보는 성의 역사", author: "필리프 브르노", genres: ["만화", "역사"], published: null, readYear: null,
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "탁월한 사유의 시선", author: "최진석", genres: ["인문"], published: 2018, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788950975401.jpg", isbn: "9788950975401",
    summary: "“추락과 도약을 가르는 건 시선의 높이다!”세상에 없던 수업, 우리가 기다려온 통찰철학 없는 시대를 위한 최진석 교수의 생각 혁명", review: "", rating: 4, quotes: [] },
  { title: "축적의 길", author: "이정동", genres: ["경제경영"], published: 2017, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791187481195.jpg", isbn: "9791187481195",
    summary: "『축적의 시간』 두 번째 이야기: 진단에서 처방으로한국산업이 처한 위기의 본질을 ‘개념설계 역량이 부족하다’라는 한 문장으로 압축해서 제시한 『축적의 시간(2015년)』이 문제의 진단이었다면 이 책은 ‘개념설계 역량을 확보하기 위해서 어떻게 도전적 시행착오의 ...", review: "", rating: 4, quotes: [] },
  { title: "히트 리프레시", author: "사티아 나델라", genres: ["경제경영"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788965965961.jpg", isbn: "9788965965961",
    summary: "클라우드를 넘어 인공지능 분야의 최고 기업으로 우뚝 선 마이크로소프트!미래를 선도하는 기업의 심연에 자리한 최고경영자 사티아 나델라의 경영 철학!“먼저, 사람과 시장, 미래에 공감하라!”위기에 빠진 기업의 ‘새로고침’ 전략!한때 IT 업계의 거인으로 군림했지만...", review: "", rating: 4, quotes: [] },
  { title: "하드씽", author: "벤 호로위츠", genres: ["경제경영"], published: 2021, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788947547031.jpg", isbn: "9788947547031",
    summary: "“진짜 문제는 그런 게 아니잖아!” a16z 공동창업자이자 실리콘밸리의 구루, 벤 호로위츠가 말하는 경영 전략의 모든 것 2021년 화제의 주인공 ‘클럽하우스’에 투자를 주도한 회사 앤드리슨호로위츠(a16z) 공동창업자이자, 휴렛패커드에 16억 달러라는 천문학...", review: "", rating: 2, quotes: [] },
  { title: "우리가 꿈꾸는 나라", author: "노회찬", genres: ["사회"], published: 2018, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788936476748.jpg", isbn: "9788936476748",
    summary: "우리는 앞으로 나아가야 합니다!자유인, 문화인, 평화인 노회찬그가 남긴 우리 사회의 과제와 해법2018년 7월 영면한 고 노회찬 의원은 학창 시절 노동운동에 몸담은 이래 진보정당 운동에 헌신해왔으며, 의정 활동 내내 약자를 대변하고 촌철살인의 언변으로 시민들에...", review: "", rating: 3, quotes: [] },
  { title: "원칙 Principles", author: "레이 달리오", genres: ["경제경영", "자기계발"], published: 2020, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791157844524.jpg", isbn: "9791157844524",
    summary: "알고 싶고, 갖고 싶은레이 달리오의 인생, 그리고 경영에 대한 원칙들!헤지펀드 브리지워터의 설립자이자 공동회장이며, 2007년 금융위기를 예측한 것으로 유명한 레이 달리오. 그는 항상 자신만의 원칙을 세워 인생, 경영, 투자 등에 적용했고, 놀라운 성과들을 보...", review: "", rating: 5, quotes: [] },
  { title: "퇴사준비생의 도쿄", author: "이동진 외", genres: ["여행"], published: 2017, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791160502114.jpg", isbn: "9791160502114",
    summary: "누구나, 언젠가, 한번쯤 퇴사준비생이 된다퇴사준비생에게 필요한 건 ‘담력’이 아니라 ‘실력’이다. 취업과 마찬가지로 퇴사에도 실력을 키우기 위한 준비가 필요하다. 회사의 브랜드, 시스템 등에 기댄 실력이 아니라 독자적인 경제생활을 하기 위한 진짜 실력 말이다....", review: "", rating: 3, quotes: [] },
  { title: "시장의 마법사들", author: "잭 슈웨거", genres: ["투자", "고전"], published: 2026, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791193394984.jpg", isbn: "9791193394984",
    summary: "월스트리트 투자 거장들의 시대를 초월한 통찰현대판 투자 고전 『시장의 마법사들』 국내 완역본의 최신 개정판이 출간됐다!트레이더들의 필수 소장 책이자전 세계 100만 부 이상 판매된 ‘시장의 마법사들’ 시리즈의 첫 번째 책!짐 로저스, 폴 튜더 존스, 리처드 데...", review: "", rating: null, quotes: [] },
  { title: "설자은, 금성으로 돌아오다", author: "정세랑", genres: ["소설", "추리"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788954695978.jpg", isbn: "9788954695978",
    summary: "『시선으로부터,』 『보건교사 안은영』 정세랑이 선보이는 본격 역사 미스터리 모험담!언제나 우리에게 놀라운 재미와 따뜻한 감동을 동시에 전해주는 작가, 정세랑이 『시선으로부터,』 이후 3년 만의 신작 장편소설 『설자은, 금성으로 돌아오다』로 돌아왔다.", review: "", rating: 4, quotes: [] },
  { title: "호텔에 관한 거의 모든 것", author: "한이경", genres: ["에세이"], published: 2021, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791191133059.jpg", isbn: "9791191133059",
    summary: "『호텔에 관한 거의 모든 것』은 ‘보이는 것부터 보이지 않은 곳까지’라는 부제에 걸맞게 호텔이 어디에서 비롯했고, 무엇으로 이루어져 있으며 과연 어디를 향하고 있는지까지를 오롯이 담고 있는 책이다. 그동안 호텔에 관한 책이란 어떤 것이었을까.", review: "", rating: 3, quotes: [] },
  { title: "왜 사업하는가", author: "이나모리 가즈오", genres: ["경제경영"], published: 2021, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791130639383.jpg", isbn: "9791130639383",
    summary: "『왜 일하는가』, 『왜 리더인가』를 잇는 이나모리 가즈오 성공 3부작의 최종 완결판!“당신은 왜 처음 그 일에 뛰어들었는가?이 질문에 답할 수 있다면 그 누구라도 다시 살아날 수 있다!”", review: "", rating: null, quotes: [] },
  { title: "만들어진 신", author: "리처드 도킨스", genres: ["과학기술", "종교"], published: 2007, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788934926184.jpg", isbn: "9788934926184",
    summary: "신의 존재를 의심하라, 인간의 능력을 주목하라!신이라는 이름 뒤에 가려진 인간의 본성과 가치를 탐색하는 세기의 문제작전세계 과학과 종교계에 파란을 일으킨 『이기적 유전자』의 저자 리처드 도킨스의 최신작이 출간되었다.", review: "", rating: 4, quotes: [] },
  { title: "세이노의 가르침", author: "세이노", genres: ["자기계발", "재테크"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791168473690.jpg", isbn: "9791168473690",
    summary: "재야의 명저 『세이노의 가르침』 2023년판 정식 출간!순자산 천억 원대 자산가, 세이노의 ‘요즘 생각’을 만나다2000년부터 발표된 그의 주옥같은 글들. 독자들이 자발적으로 만든 제본서는 물론, 전자책과 앱까지 나왔던 『세이노의 가르침』이 드디어 전국 서점에...", review: "", rating: 4, quotes: [] },
  { title: "내가 확실히 아는 것들", author: "오프라 윈프리", genres: ["에세이", "자기계발"], published: 2024, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791164052745.jpg", isbn: "9791164052745",
    summary: "세계에서 가장 성공한 여성 오프라 윈프리의자전적 에세이 『내가 확실히 아는 것들』 출간 10주년 기념 증보판 한미 동시 출간 개정판 서문, 에세이 ‘마음 씀(Caring)’ 추가 [타임] 선정 ‘20세기의 위대한 인물’, [포브스] 선정 ‘세계에서 가장 영향력...", review: "", rating: 3, quotes: [] },
  { title: "초판본 주홍색 연구", author: "아서 코넌 도일", genres: ["소설", "추리", "고전"], published: null, readYear: null,
    summary: "", review: "", rating: 5, quotes: [] },
  { title: "어차피 일할 거라면, Porto", author: "하경화·이혜민", genres: ["여행", "에세이"], published: 2019, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791159000553.jpg", isbn: "9791159000553",
    summary: "취향을 파는 미디어 회사 ‘디에디트’의 유럽 출근 판타지“하고 싶은 일을 하고 싶어서 회사를 차렸는데 행복하지 않았다.” ‘디에디트’의 하경화 & 이혜민, 두 대표는 회사를 통째로 옮겨 보자 결심한다. “낯선 도시에 살면서 일하는 것, 재밌을 것 같지 않아?”...", review: "", rating: 3, quotes: [] },
  { title: "있으려나 서점", author: "요시타케 신스케", genres: ["만화"], published: 2019, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788934981237.jpg", isbn: "9788934981237",
    summary: "『이게 정말 사과일까?』의 일본 천재 그림책 작가, 요시타케 신스케가 그리는 상상 서점! ‘책에 관한, 책을 위한, 책에 의한’ 모든 것이 담긴, 명실상부한 ‘책’에 관한 책이다. 책을 좋아하는 독자뿐만 아니라 책과 관련된 일에 종사하는 모든 사람들이 고개를...", review: "", rating: 2, quotes: [] },
  { title: "연의 편지", author: "조현아", genres: ["만화"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791196155773.jpg", isbn: "9791196155773",
    summary: "편지와 함께 찾아온 마법 같은 시간낯설고 두려운 순간, 나를 인도하듯 날아온 편지와 그 안에 적힌 수수께끼.편지를 따라가면 너를 만날 수 있을까…?극장판 애니메이션 개봉 기념 ‘리커버 양장본’ 구성와이드 표지 일러스트 엽서 4장 + 도서 대출 카드 + 작가님 ...", review: "", rating: 3, quotes: [] },
  { title: "12가지 인생의 법칙", author: "조던 B. 피터슨", genres: ["자기계발"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791190538534.jpg", isbn: "9791190538534",
    summary: "전 세계를 뒤흔든 조던 피터슨의 대표작새로운 한국어판 서문이 수록된 40만 부 기념 특별판전 세계 50개국에서 600만 부가 넘게 팔리며 수많은 젊은이들이 인생 책으로 꼽는 조던 피터슨의 대표작 『12가지 인생의 법칙』이 국내 40만 부 판매를 기념하여 새로운...", review: "", rating: 5, quotes: [] },
  { title: "잘돼가? 무엇이든", author: "이경미", genres: ["에세이"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791197852084.jpg", isbn: "9791197852084",
    summary: "영화감독 이경미의 첫 번째 에세이, 5년 만의 개정증보판새로운 글과 삽화로 만나는 2018년 이후 5년간의 이야기“나의 혼잣말이 책이 될 줄 알았다면 이만큼 솔직하지 못했을 것이다.`[미쓰 홍당무] [비밀은 없다] [보건교사 안은영]의 감독 이경미가 쓴 첫 번...", review: "", rating: null, quotes: [] },
  { title: "노르웨이의 숲", author: "무라카미 하루키", genres: ["소설"], published: 2017, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788937434488.jpg", isbn: "9788937434488",
    summary: "“나를 언제까지나 잊지 마, 내가 여기 있었다는 걸 기억해 줘.”하루키 월드의 빛나는 다이아몬드무라카미 하루키를 만나기 위해 가장 먼저 읽어야 할 책!페이지를 처음 펼치는 오늘의 젊음들에게, 그리고 오랜 기억 속에 책의 한 구절을 간직하고 있는 어제의 젊음들에...", review: "", rating: 3, quotes: [] },
  { title: "네이비씰 승리의 기술", author: "조코 윌링크·레이프 바빈", genres: ["경제경영"], published: 2019, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791196509460.jpg", isbn: "9791196509460",
    summary: "100만 독자의 삶을 바꾼 최강의 멘탈 트레이닝『네이비씰 승리의 기술』은 세계 최강 특수 부대 네이비씰 출신 저자가 전쟁터에서 목숨 걸고 싸우며 얻은 승리의 기술을 열두 가지 원칙으로 정리한 책이다. 네이비씰은 미국 국방성의 승인을 거쳐 세상에 처음으로 공개되...", review: "", rating: 3, quotes: [] },
  { title: "실격당한 자들을 위한 변론", author: "김원영", genres: ["사회"], published: 2018, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791160943733.jpg", isbn: "9791160943733",
    summary: "‘인간 실격’이란 없다 세상에 태어난 것 자체가 손해인 삶이 있을까? 평생을 방에 누워 있어야 하는 중대한 장애, 자식에게 밥 한 끼 먹이기 어려운 처절한 빈곤, 누구에게도 호감을 사본 적 없는 추한 외모나 다른 성적 지향…….", review: "", rating: 3, quotes: [] },
  { title: "오늘도 펭수 내일도 펭수", author: "EBS·펭수", genres: ["에세이"], published: 2019, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791130627366.jpg", isbn: "9791130627366",
    summary: "출간 즉시 주요 서점 종합베스트 1위펭수와 매일 함께하고 싶은 당신께 권하는“오늘도 펭수 내일도 펭수”펭-하! 140만 구독자의 마음을 사로잡은 자이언트 펭귄 펭수의 에세이 다이어리 『오늘도 펭수 내일도 펭수』가 출간되었다.", review: "", rating: 3, quotes: [] },
  { title: "한자와 나오키 3", author: "이케이도 준", genres: ["소설"], published: 2019, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791189995119.jpg", isbn: "9791189995119",
    summary: "“그들이 반칙을 쓰더라도 우리는 정면승부야!”세상의 부조리에 맞서는 은행원 한자와의 통쾌한 미스터리 활극시리즈 누적 판매부수 607만 부, 일본 초대형 베스트셀러!2020년 드라마 [한자와 나오키] 시즌2 원작 소설!『한자와 나오키』 시리즈의 세 번째 책 『한...", review: "", rating: 5, quotes: [] },
  { title: "전설로 떠나는 월가의 영웅", author: "피터 린치·존 로스차일드", genres: ["투자", "고전"], published: 2026, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788957822678.jpg", isbn: "9788957822678",
    summary: "월가의 전설적인 투자자 ‘피터 린치’가 쓴 주식투자의 고전!새로운 번역, 더 깊어진 이해. 투자 고전을 다시 만나다“어떤 기업이든 공부하지 않고 주식을 사면, 카드를 보지 않고 포커게임에 임하는 것과 같다. 사람들이 부동산에서 돈을 벌고 주식에선 돈을 잃는 이...", review: "", rating: 4, quotes: [] },
  { title: "사장의 마음", author: "김일도", genres: ["경제경영"], published: 2019, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791187289609.jpg", isbn: "9791187289609",
    summary: "특별한 식당을 만드는 사장의 한결같은 마음해답이 아닌 조언이 절실하다면?자영업자 700만 명 시대, 오늘도 크고 작은 가게에서 수많은 사장들이 문을 열고 문을 닫는다. 여기서 드는 의문 하나, 장사 잘하는 법을 다룬 책은 많은데, 어째서 사장들의 마음을 어루만...", review: "", rating: 3, quotes: [] },
  { title: "쓸 만한 인간", author: "박정민", genres: ["에세이"], published: 2020, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791190938198.jpg", isbn: "9791190938198",
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "달콤한 숨결", author: "유즈키 유코", genres: ["소설", "스릴러"], published: 2021, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788934949077.jpg", isbn: "9788934949077",
    summary: "일본추리작가협회상, ‘이 미스터리가 대단하다! 대상’, 서점대상 2위… 차세대 스토리텔러 유즈키 유코의 전율적 사회파 범죄 미스터리!『고독한 늑대의 피』 『검사의 숙원』 등 이른바 ‘남자의 이야기’를 능수능란하게 다루는 솜씨로 찬탄받던 유즈키 유코.", review: "", rating: 4, quotes: [] },
  { title: "어린이라는 세계", author: "김소영", genres: ["에세이"], published: 2020, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791160946918.jpg", isbn: "9791160946918",
    summary: "어린이에 대해 생각할수록 우리의 세계는 넓어진다어린이는 잘 보이지 않는다. 몸이 작아서이기도 하고, 목소리가 작아서이기도 하다. 양육이나 교육, 돌봄을 맡고 있는 사람이 아니라면 우리 곁에 어린이가 ‘있다’는 사실을 의식하지 못한 채 살아가기 쉽다.", review: "", rating: 4, quotes: [] },
  { title: "유난한 도전", author: "정경화", genres: ["경제경영"], published: 2022, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791191211863.jpg", isbn: "9791191211863",
    summary: "세상에 없던 금융, 세상에 없던 일 문화를 만드는 사람들, 토스928억 시간. 2015년 토스 앱이 나온 후, 사용자들이 간편송금으로 아낀 시간을 모두 합하면 928억 시간이 넘는다. 대한민국 성인 2.5명 중 한 명은 토스 앱에서 자신의 신용점수를 확인하고,...", review: "", rating: 5, quotes: [] },
  { title: "입지 센스", author: "박성혜(휠휠)", genres: ["재테크"], published: 2022, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791130692074.jpg", isbn: "9791130692074",
    summary: "“똑같은 돈을 가지고 왜 누군가는 상급지로 올라가고, 누군가는 하급지에 머무르는가?”입지 분석 전문가 훨훨이 족집게 과외처럼 알려주는평범한 월급쟁이도 강남에 입성하는 전략적 부의 로드맵- 빠숑 김학렬 강력 추천! - ‘월부TV’, ‘집코노미TV’ 화제의 부동산...", review: "", rating: 2, quotes: [] },
  { title: "편집광만이 살아남는다", author: "앤드류 그로브", genres: ["경제경영"], published: 2021, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788960518711.jpg", isbn: "9788960518711",
    summary: "비즈니스와 커리어 성공과 몰락의 갈림길, 변곡점!이 절체절명의 위기에서 어떻게 살아남아 승자가 될 것인가?반도체 제국 인텔을 건설한 전설적 CEO이자 디지털 혁명을 선도한 실리콘 밸리와 컴퓨터 산업의 “전설” 앤드루 그로브가 쓴 현대 경영의 고전.", review: "", rating: 4, quotes: [] },
  { title: "연애의 기술", author: "송선미", genres: [], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791190067645.jpg", isbn: "9791190067645",
    summary: "“나는 왜 항상 ‘을의 연애’를 할까?”그 사람의 연락을 항상 기다린다. 나에 비해 그는 내게 크게 관심이 없다.그 사람이 원하는 것과 내가 원하는 것이 달라도 내 주장을 하지 못한다.그 사람이 헤어지자고 할까 두렵다.“이런 말들에 내 얘기라고 생각한다면 당신...", review: "", rating: null, quotes: [] },
  { title: "사랑의 기술", author: "에리히 프롬", genres: ["고전", "심리"], published: 2026, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788931027068.jpg", isbn: "9788931027068",
    summary: "“사랑은 감정이 아니라 기술이다”에리히 프롬의 《사랑의 기술》 출간 70주년 · 한국어판 50주년 기념! 강주헌의 번역으로 새롭게 태어난 전면 개정판1956년 첫 출간 이후 34개 이상의 언어로 번역되며 전 세계 수백만 독자의 삶을 바꾼 현대 인문학의 불멸의 ...", review: "", rating: 5, quotes: [] },
  { title: "영혼의 설계자", author: "그레그 호프먼", genres: ["마케팅"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791130698229.jpg", isbn: "9791130698229",
    summary: "“우리는 신발을 팔지 않는다.영원히 기억될 위대한 유산을 남긴다!”말단 디자이너에서 최고마케팅책임자까지‘나이키 세계관’을 이끈 실질적 수장그레그 호프먼이 기록한 27년간의 퍼포먼스", review: "", rating: 5, quotes: [] },
  { title: "도쿄 타워", author: "에쿠니 가오리", genres: ["소설"], published: 2020, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791160271775.jpg", isbn: "9791160271775",
    summary: "세련된 문체와 섬세한 심리묘사로 사랑 받아온 에쿠니 가오리의 장편소설 『도쿄 타워』는 이제 막 스무 살이 된 남자 아이들과 그들에게 찾아온 연상의 연인들과의 사랑 이야기를 담았다. 도쿄 타워가 지켜봐 주는 장소의 이야기를 쓰고 싶었다는 작가는, 특유의 감각적인...", review: "", rating: 3, quotes: [] },
  { title: "지도 끝의 모험", author: "릭 리지웨이", genres: ["에세이", "여행"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791197874390.jpg", isbn: "9791197874390",
    summary: "2022 내셔널 아웃도어 북 어워드 수상작!파타고니아 지속가능경영 부사장 릭 리지웨이가 35년간 지구 끝 미지의 땅을 탐험하며 깨달은 것들세상의 가장 외딴 곳 작은 텐트에서 보내온 인간과 야생, 공존의 철학미국인 최초 K2 무산소 등정, 보르네오 최장 코스 횡...", review: "", rating: 4, quotes: [] },
  { title: "도둑맞은 집중력", author: "요한 하리", genres: ["심리"], published: 2024, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791167740984.jpg", isbn: "9791167740984",
    summary: "조승연, 유현준, 김겨울 추천 도서전 세계 모든 곳에서, 집중하는 우리의 능력은 붕괴하고 있다. 미국의 10대들은 한 가지 일에 65초 이상 집중하지 못한다. 직장인들의 평균 집중 시간은 단 3분에 불과하다. 뉴...", review: "", rating: 3, quotes: [] },
  { title: "변두리 로켓", author: "이케이도 준", genres: ["소설"], published: 2020, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791191056273.jpg", isbn: "9791191056273",
    summary: "변두리 작은 공장의 신화가 시작된다!초대형 베스트셀러 ‘한자와 나오키’ 이케이도 준의우직한 열정과 감동의 휴먼 드라마145회 나오키상 수상작시리즈 누적 350만 부 돌파! 아마존 · 기노쿠니야 소설 1위일본 최고의 스토리텔러 이케이도 준의 대표작 『변두리 로켓...", review: "", rating: 4, quotes: [] },
  { title: "1타 7피 주식 초보 최고 계략", author: "박성현", genres: ["투자"], published: 2020, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791188754328.jpg", isbn: "9791188754328",
    summary: "‘유리 멘털 동학 개미’도 고수 뺨치는 투자 가능한초간단 룰 베이스 매매 전략, 세븐 스플릿 시스템“7개의 주식 계좌가 ‘7개의 투자 자아’로 나뉘어 상승장에도 하락장에도 365일 수익을 실현한다”주식 초보도 따라만 하면 효과 있는 쉽고 간단한 투자 방법이 있...", review: "", rating: 3, quotes: [] },
  { title: "아홉 명의 완벽한 타인들", author: "리안 모리아티", genres: ["소설"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788947549097.jpg", isbn: "9788947549097",
    summary: "전 세계 2000만 부 판매 베스트셀러 작가 리안 모리아티 화제의 컬렉션“여기를 떠날 때, 전혀 다른 사람이 돼 있고 싶은가요?”한 지붕 아래 모인 낯선 사람들…수상한 열흘, 모든 것이 차단된 삶이 시작된다! 몸과 마음을 치유하기로 이름난 최고급 건강휴양지 ...", review: "", rating: 3, quotes: [] },
  { title: "벤 버냉키의 21세기 통화 정책", author: "벤 S. 버냉키", genres: ["경제경영"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791192389219.jpg", isbn: "9791192389219",
    summary: "2022년 노벨경제학상 수상자 벤 버냉키의 신간돈 공부, 경제 공부를 위한 이 시대의 필독서세계 경제를 움직이는 연준의 모든 것을 담은 책『벤 버냉키의 21세기 통화 정책』은 2022년 노벨경제학상 수상자이자 미국 연방준비제도의 의장이었던 벤 버냉키의 내공이 ...", review: "", rating: 5, quotes: [] },
  { title: "앞으로 3년 경제전쟁의 미래", author: "오건영", genres: ["경제경영"], published: 2019, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791187481607.jpg", isbn: "9791187481607",
    summary: "금리와 환율로 세계 경제의 흐름과 미래를 읽는다!금융위기의 원인을 분석하고 대안을 제시한 책들은 지나치게 전문적이고 방대해 일반인들이 읽기에 어려웠다. 화폐전쟁과 환율전쟁을 다룬 책들은 현 세계 경제의 특징을 제시했지만 세계 경제의 실질적 흐름을 읽기에는 너무...", review: "", rating: 3, quotes: [] },
  { title: "언스크립티드 부의 추월차선 완결판", author: "엠제이 드마코", genres: ["재테크"], published: 2018, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791187444213.jpg", isbn: "9791187444213",
    summary: "일주일에 5일을 노예처럼 일하고다시 노예처럼 일하기 위해 2일을 쉬고 있는가?“당신을 가난으로 이끄는 조작된 각본에서 탈출하라!”아마존 경제경영 분야 1위 / 국내 온·오프 전 서점 1위 석권 / 10개 국어가 넘는 언어로 출간된 국제적 베스트셀러 『부의 추월...", review: "", rating: 5, quotes: [] },
  { title: "명탐정 코난 흔들리는 경시청 1200만 명의 인질", author: "아오야마 고쇼", genres: ["만화"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791136775528.jpg", isbn: "9791136775528",
    summary: "7년 전 11월 7일에는 폭탄을 해체하던 하기와라 켄지를, 3년 전 11월 7일에는 몸 바쳐 또 다른 폭탄의 행방을 알아낸 마츠다 진페이를 죽음에 몰아넣은 연쇄 폭파범이 또다시 움직이기 시작한다! 마츠다를 사모했던 사토 형사의 흔들리는 마음.", review: "", rating: 3, quotes: [] },
  { title: "달리기를 말할 때 내가 하고 싶은 이야기", author: "무라카미 하루키", genres: ["에세이"], published: 2009, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788970128337.jpg", isbn: "9788970128337",
    summary: "달리기에 대해 정직하게 쓴다는 것은나라는 인간에 대해서 정직하게 쓰는 일이기도 했다 - 무라카미 하루키서머싯 몸은 `어떤 면도의 방법에도 철학이 있다`라고 말했다. 아무리 하찮은 일이라도 매일 계속하다 보면 나름의 철학이 우러난다는 뜻일 게다.", review: "", rating: 5, quotes: [] },
  { title: "언러키 스타트업", author: "정지음", genres: ["에세이"], published: 2022, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788937427343.jpg", isbn: "9788937427343",
    summary: "「좋좋소」보다 눈물겹고 「술꾼 도시 여자들」 만큼 유쾌하다!『젊은 ADHD의 슬픔』 정지음 작가 첫 소설통통 튀는 유머로 그리는 스타트업의 웃픈 현실『젊은 ADHD의 슬픔』을 통해 단번에 주목할 작가로 떠오른 정지음의 첫 소설 『언러키 스타트업』이 민음사에서 ...", review: "", rating: 4, quotes: [] },
  { title: "오민혁 단편선 화점", author: "오민혁", genres: ["소설"], published: 2020, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788966073214.jpg", isbn: "9788966073214",
    summary: "기상천외한 상상력으로 빚어낸, 오민혁의 유일무이한 작품 세계!네이버웹툰 화제작 「화점」을 포함한 다섯 편의 연재작과 미발표 신작 「우주어(宇宙魚)」까지 총 여섯 편 수록!“천재가 나타났다!” 오민혁 작가의 작품을 봤다면 공감할 수밖에 없는 말이다.", review: "", rating: 4, quotes: [] },
  { title: "모순", author: "양귀자", genres: ["소설"], published: 2013, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788998441012.jpg", isbn: "9788998441012",
    summary: "초판이 나온 지 벌써 15년이 흘렀지만 이 소설 『모순』은 아주 특별한 길을 걷고 있다. 그때 20대였던 독자들은 지금 결혼을 하고 30대가 되어서도 가끔씩 『모순』을 꺼내 다시 읽는다고 했다. 다시 읽을 때마다 전에는 몰랐던 소설 속 행간의 의미를 깨우치거나...", review: "", rating: null, quotes: [] },
  { title: "살려 마땅한 사람들", author: "피터 스완슨", genres: ["소설", "스릴러"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791156754374.jpg", isbn: "9791156754374",
    summary: "스릴러 팬들을 또 한 번 흥분시킬 전 세계 33개국 출간 베스트셀러 『죽여 마땅한 사람들』 후속작 출간!『죽여 마땅한 사람들』로 국내외 스릴러 독자들로부터 단숨에 명성을 거머쥔 작가 피터 스완슨의 신작 『살려 마땅한 사람들』이 도서출판 푸른숲에서 출간되었다.", review: "", rating: 3, quotes: [] },
  { title: "스토너", author: "존 윌리엄스", genres: ["소설"], published: 2015, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788925554990.jpg", isbn: "9788925554990",
    summary: "“사는 모습은 달라도, 우리는 누구나 스토너다.” 조용하고 절망적인 생에 관한 소박한 이야기,그러나 50년의 시차를 지나 전 세계인의 마음을 사로잡은 위대한 이야기!2013 워터스톤 올해의 책 영국, 프랑스, 독일, 네덜란드 등 전 유럽 베스트셀러출간 후 50...", review: "", rating: 5, quotes: [] },
  { title: "현명한 투자자", author: "벤저민 그레이엄", genres: ["투자", "고전"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788957822401.jpg", isbn: "9788957822401",
    summary: "워런 버핏이 최고의 투자서라고 극찬한 투자서의 고전가치투자의 아버지 벤저민 그레이엄이 주식투자자에게 전하는 마지막 선물가치투자의 아버지 벤저민 그레이엄의 《현명한 투자자》는 1949년 초판 이래 개정2, 3판을 거쳐 1973년에 개정4판을 발행했다.", review: "", rating: 4, quotes: [] },
  { title: "투자는 심리게임이다", author: "앙드레 코스톨라니", genres: ["투자"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791192519890.jpg", isbn: "9791192519890",
    summary: "전설적인 투자자, 앙드레 코스톨라니가 들려주는 투자의 정글에서 살아남기증권시장의 모든 데이터들을 아는 것만으로 코스톨라니는 만족하지 못했다. 그에게는 ‘환상’이 성공적인 투자와 예측의 엔진으로 남아 있었다. 그리하여 그는 조직적 투기와 증권시장의 컴퓨터들을 경...", review: "", rating: 3, quotes: [] },
  { title: "호텔 프린스", author: "안보윤 외", genres: ["소설"], published: 2017, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788956604183.jpg", isbn: "9788956604183",
    summary: "책이 된 호텔, ‘소설가의 방’에 체크인하다 호텔에서 피어난 아름다운 소설 실험!은행나무 테마소설 시리즈 바통, 첫 번째 권 누군가에게는 여행의 공간, 또 누구에게는 사색의 공간이자 일탈의 공간, ‘호텔’을 소재로 한 테마소설집 『호텔 프린스』가 출간되...", review: "", rating: 1, quotes: [] },
  { title: "루팡의 딸", author: "요코제키 다이", genres: ["소설"], published: 2021, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791190157407.jpg", isbn: "9791190157407",
    summary: "홈즈의 딸이 루팡의 아들을 만났다!일명 홈즈의 딸인 미쿠모는 운명의 남자를 만나 사랑에 빠진다. 그 남자의 정체는 L의 일족이라 불리는 도둑 집안의 아들 와타루. 미쿠모의 파트너이자 와타루의 매부인 카즈마는 이 금단의 사랑을 말려보지만, 남자친구의 정체를 모르...", review: "", rating: 2, quotes: [] },
  { title: "돈, 뜨겁게 사랑하고 차갑게 다루어라", author: "앙드레 코스톨라니", genres: ["투자", "고전"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791192519883.jpg", isbn: "9791192519883",
    summary: "앙드레 코스톨라니 최후의 역작으로 증권 거래와 투자심리에 중요한 변수인 투자의 근본적인 비밀과 기술 등을 안내한 돈 관리 지침서다. 저자는 투자자들에게 21세기 증권시장에 있어서 기회와 위험, 그리고 변화와 상승, 하락에 대한 전망을 보여준다.", review: "", rating: 5, quotes: [] },
  { title: "에밀리의 작은 부엌칼", author: "모리사와 아키오", genres: ["소설"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788976046178.jpg", isbn: "9788976046178",
    summary: "한 편의 영화처럼 자아의 성장과 치유 과정을산뜻하고 화창하게 그린 소설! 누군가가 ‘나’를 위해 차려준 한 끼의 정성스러운 식사만으로도 상처받은 자아는 치유의 기력을 회복하고 새로운 삶의 희망을 품게 된다. 사실상 삶의 기적은 대단한 것이 아니다.", review: "", rating: null, quotes: [] },
  { title: "한국형 가치투자", author: "최준철·김민국", genres: ["투자"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791189318413.jpg", isbn: "9791189318413",
    summary: "3조 이상을 운용 중인 VIP 자산운용 최준철, 김민국이마침내 공개하는 가치투자 바이블『한국형 가치투자』는 『한국형 가치투자 전략』과 『가치투자가 쉬워지는 V차트』를 잇는 가치투자 3부격이다. 『한국형 가치투자 전략』이 가치투자의 개념과 올바른 종목 선정법, ...", review: "", rating: 3, quotes: [] },
  { title: "그림자 인간", author: "츠지도 유메", genres: ["소설"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788972773801.jpg", isbn: "9788972773801",
    summary: "일본 최대 독서 커뮤니티의 꼭 읽고 싶은 책일본 문단에서 가장 주목받는 여류 추리소설가 츠지도 유메의 역작!살인 미수 사건의 용의자가 무호적자인 ...", review: "", rating: 3, quotes: [] },
  { title: "이반 일리치의 죽음", author: "레프 톨스토이", genres: ["소설", "고전"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788937464386.jpg", isbn: "9788937464386",
    summary: "“모든 것이 한결같다. 세월이 흐를수록 더욱 죽음 같다. 산을 오른다고 상상하지만 사실은 꾸준히 산 아래로 내려가고 있었다. 산을 오르는 만큼 삶은 내 밑으로 떠내려가고 있었던 것이다.” -본문에서러시아를 대표하는 문호이자 전 세계 사람들의 삶과 가치관에 심오...", review: "", rating: 5, quotes: [] },
  { title: "오만과 편견", author: "제인 오스틴", genres: ["소설", "고전"], published: 2003, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788937460883.jpg", isbn: "9788937460883",
    summary: "셰익스피어의 뒤를 이어 ‘지난 천 년간 최고의 문학가’로 꼽힌 제인 오스틴결혼을 마주한 여성들이 헤쳐 나가야 하는 현실적인 난관,그리고 애정이라는 조건을 예리하게 묘파한 고전 중의 고전 “제가 장담하는데 당신은 저한테서 좋은 점을 하나도 찾지 못했어요.", review: "", rating: 5, quotes: [] },
  { title: "사람은 무엇으로 사는가", author: "레프 톨스토이", genres: ["소설", "고전"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788937464720.jpg", isbn: "9788937464720",
    summary: "“이제 난 깨달았다. 사람들에게는 자신이 스스로에 대한 염려 덕에 살아 있는 것처럼 보이겠지만 그들이 살아 있는 것은 오직 사랑 때문이다.”『전쟁과 평화』, 『안나 카레니나』의 거장 톨스토이가깊은 우울과 방황의 끝에서 발견한 최후의 통찰글을 모르는 사람도 마음...", review: "", rating: 3, quotes: [] },
  { title: "보도 섀퍼 부의 레버리지", author: "보도 섀퍼", genres: ["재테크"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791162543269.jpg", isbn: "9791162543269",
    summary: "아직도 일한 만큼 버는가? 무조건 1년 안에 수입의 20%부터 늘려라!!세계적인 머니멘토 ‘보도 섀퍼’가 직접 찾아낸 경제적 자유를 얻는 법!20년 전, 보도 섀퍼가 자신이 어떻게 완전한 경제적 자유를 이뤘는지 밝힌 저서가 업그레이드된 부의 공식과 마인드셋을 ...", review: "", rating: 3, quotes: [] },
  { title: "크리스마스 타일", author: "김금희", genres: ["소설"], published: 2022, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788936438890.jpg", isbn: "9788936438890",
    summary: "열심히 사랑하고 이별한 모든 이들을 위한 소설마음을 환하게 밝히는 작가 김금희의 크리스마스 선물 같은 이야기수많은 독자에게 사랑받는 작가 김금희가 데뷔 13년 만에 첫번째 연작소설을 선보인다. 크리스마스를 배경으로 한 명랑하고 아름다운 이야기를 반짝이는 일곱편...", review: "", rating: 1, quotes: [] },
  { title: "기술적 분석 모르고 절대 주식투자 하지 마라", author: "잭 슈웨거", genres: ["투자"], published: 2019, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791188279593.jpg", isbn: "9791188279593",
    summary: "『시장의 마법사들』 잭 슈웨거가 직접 밝히는 실전 기술적 분석의 모든 것 선물, 헤지펀드 전문가이자 『시장의 마법사들』을 비롯한 다수의 베스트셀러를 낸 잭 슈웨거가 실전과 경험을 통해 터득한 기술적 분석의 개념과 기법을 공개한다!", review: "", rating: 3, quotes: [] },
  { title: "더 레슨", author: "스콧 A. 채프먼", genres: ["투자"], published: 2022, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791165219765.jpg", isbn: "9791165219765",
    summary: "역사상 가장 뛰어난 투자자인 존 템플턴, 피터 린치, 워런 버핏에게 배운다‘더 레슨’, 거장의 투자 철학과 전략에서 뽑아낸 성공 투자의 원칙 -대가들의 실증적 자료, 투자 포트폴리오, 개별 투자사례, 투자 원칙, 철학, 지혜… -세 거장의 공통점으로 만든 모...", review: "", rating: 4, quotes: [] },
  { title: "어느 주식투자자의 회상", author: "에드윈 르페브르", genres: ["투자", "고전"], published: 2024, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791193394229.jpg", isbn: "9791193394229",
    summary: "가치투자법과 더불어 오늘날 주식매매기법의 커다란 한 축을 형성하고 있는 추세매매법을 확립하여 ‘추세매매법의 아버지’로 불리는 제시 리버모어가 사사건건 부딪쳐야만 했던 실제 상황 속에서 어떻게 자신의 매매기법을 개발했고 적용해 나갔는지를 담고 있는 책이다.", review: "", rating: 4, quotes: [] },
  { title: "레슨 인 케미스트리 2", author: "보니 가머스", genres: ["소설"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791130646787.jpg", isbn: "9791130646787",
    summary: "애플TV+ 드라마 [레슨 인 케미스트리] 원작 소설65세 신인 작가가 데뷔작으로 이룬 놀라운 기록2022년 봄, 예순다섯 살 신인 작가의 데뷔 소설 『레슨 인 케미스트리』가 출간되었다. 저자는 어떤 명성도 없었고, 작가로서의 경력은 전무했다.", review: "", rating: 5, quotes: [] },
  { title: "주식시장의 승부사들", author: "한봉호 외", genres: ["투자"], published: 2020, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791188279890.jpg", isbn: "9791188279890",
    summary: "실전투자대회 입상 기록 48회 이상, 합산 우승 22회! 전설로 남을 주식투자자의 이야기 전쟁터 같은 실전에서 자신을 증명한 최강자들에게 배우는 투자 전략, 심리컨트롤, 생존 비법 매해 증권사에서 개최하는 실전투자대회에는 전국의 내로라하는 주식투자의 고수들이 ...", review: "", rating: 4, quotes: [] },
  { title: "세력주의 신 100법칙", author: "이시이 카츠토시", genres: ["투자"], published: null, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788965023227.jpg", isbn: "9788965023227",
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "돌파매매 전략", author: "systrader79(이우근)·김대현", genres: ["투자"], published: 2024, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791193394168.jpg", isbn: "9791193394168",
    summary: "이 책은 신이 내린 책이다_강환국현존 최강의 전략을 국내 주식시장에 적용시킨 최초의 서적!니콜라스 다바스, 윌리엄 오닐, 마크 미너비니, 데이비드 라이언, 댄 쟁거 등 전설적인 트레이더들이 공통적으로 사용한 전략인 돌파매매 기법을 다룬 책이다.", review: "", rating: 4, quotes: [] },
  { title: "쓰다 보니, 쓸 만해졌습니다", author: "위한솔", genres: ["에세이", "글쓰기"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791193262450.jpg", isbn: "9791193262450",
    summary: "원의독백, 박신영, 이승희(숭), 리니 강력 추천!“요즘 ‘일잘러’들은 기록으로 성장합니다.”기록을 통해 나의 활용도를 높이는 브랜드 마케터, 위씨리스트(@wi_see_list)의 성장 에세이『쓰다 보니, 쓸 만해졌습니다』는 브랜드 마케터인 위한솔 저자...", review: "", rating: 3, quotes: [] },
  { title: "소득혁명", author: "브라이언 페이지", genres: ["재테크"], published: 2024, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791193904251.jpg", isbn: "9791193904251",
    summary: "“나의 아버지는 수십 년간 영혼을 박살 내는 일에 매여 살았으나 처절히 가난했고, 일흔이 넘어서는 흑색종 4기 진단을 받았다. 은퇴는 했으나 이미 아무것도 할 수 없는 몸이었다. 아버지의 마지막 모습은 내 가슴에 불을 지폈다.", review: "", rating: 5, quotes: [] },
  { title: "돈을 부르는 매너", author: "민경남", genres: ["자기계발"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791168476073.jpg", isbn: "9791168476073",
    summary: "돈, 벌지 말고 불러 보세요!『돈을 부르는 매너』“매너와 자산은 비례할까?”어느 날 떠오른 의문에서 출발한 수년간의 기록.돈을 부르고 인생을 바꾸는 매너 이야기.부동산 투자 전문가로서 일하던 저자는 큰돈을 운용하는 이들의 공통점을 발견한다.", review: "", rating: 2, quotes: [] },
  { title: "파이어 인 더 홀", author: "밥 파슨스·로라 모튼", genres: ["경제경영"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791140714438.jpg", isbn: "9791140714438",
    summary: "역경을 넘어 폭발적인 성공을 이루기까지 《파이어 인 더 홀》“이 책을 펼치는 순간부터 당신의 인생은 이미 앞으로 움직이기 시작한다.”고대디, PXG를 창업한 억만장자 사업가의 성공 조언구제 불능 학생, 베트남전 참전 용사에서고대디, PXG 창업자가 되기까지억만...", review: "", rating: 5, quotes: [] },
  { title: "스타트업 설계자", author: "제프 워커", genres: ["경제경영"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791155818084.jpg", isbn: "9791155818084",
    summary: "53분 만에 100만 달러 매출의 전설, 미국 마케팅 업계를 뒤흔든 단 하나의 공식 ‘PLF’", review: "", rating: 3, quotes: [] },
  { title: "나는 거인에게 억만장자가 되는 법을 배웠다", author: "앤드루 윌킨슨", genres: ["경제경영"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788901294315.jpg", isbn: "9788901294315",
    summary: "“거인을 존경하던 아버지는 평생 가난했고,거인을 따라 한 나는 억만장자가...", review: "", rating: 5, quotes: [] },
  { title: "그리고 아무도 없었다", author: "애거서 크리스티", genres: ["소설", "추리", "고전"], published: 2013, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788960177758.jpg", isbn: "9788960177758",
    summary: "전 세계 미스터리의 역사를 재창조한 추리 소설의 여왕,애거서 크리스티를 대표하는 작품만을 모은 에디터스 초이스1억 부 이상이 팔린 명실공히 최고의 애거서 크리스티 소설이자, 출간 이래 항상 세계에서 가장 많이 팔리고 있는 미스터리 소설!", review: "", rating: 4, quotes: [] },
  { title: "우리는 왜 성공할수록 불안해할까", author: "밸러리 영", genres: ["심리"], published: 2024, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791191842753.jpg", isbn: "9791191842753",
    summary: "가면 증후군은 어떻게 우리의 성장을 가로막는가?임포스터 연구의 세계적 권위자 밸러리 영이제안하는 자기성취의 주인이 되는 법- 자신의 성공이 행운, 타이밍, 인맥, 성격 때문이라고 생각하는가? - ‘내가 할 수 있다면 누구든 할 수 있다’고 생각하는가?", review: "", rating: 3, quotes: [] },
  { title: "필터 없이", author: "폴리나 포리즈코바", genres: ["에세이"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791193063958.jpg", isbn: "9791193063958",
    summary: "타인의 시선을 걷어내고 마침내 ‘진짜 나’를 마주한 한 여자의 고백폴리나 포리즈코바는 열다섯 살에 모델로 데뷔해 전 세계의 스포트라이트를 받으며 ‘아름다움’의 아이콘이 되었다. 하지만 이 책에서 그녀는 그 화려한 얼굴 뒤에 감춰왔던 불안과 상처, 모순과 상실의...", review: "", rating: 3, quotes: [] },
  { title: "진짜의 마인드", author: "김찬희(김진짜)", genres: ["자기계발"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791193650189.jpg", isbn: "9791193650189",
    summary: "생각의 잡음을 제거하면 모든 순간은 기회가 된다일, 사람 그리고 나모든 문제를 터닝 포인트로 바꾸는 진짜의 통찰!", review: "", rating: 3, quotes: [] },
  { title: "나폴레온 힐 성공의 법칙", author: "나폴레온 힐", genres: ["자기계발"], published: 2023, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791169850070.jpg", isbn: "9791169850070",
    summary: "“성공한 사람들의 서재에는 늘 이 책이 있었다!”밥 프록터, 토니 로빈슨, 조셉 머피를 만든 스승 ‘나폴레온 힐’지금까지의 성공 철학은 모두 이 책에서 시작되었다!", review: "", rating: 4, quotes: [] },
  { title: "끌어당김", author: "나폴레온 힐 외", genres: ["자기계발"], published: 2022, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791197552816.jpg", isbn: "9791197552816",
    summary: "데일 카네기, 워런 버핏, 오프라 윈프리, 론다 번, 빌 클린턴 대통령 등 수많은 이들에게 섬광처럼 다가왔던 성공의 비밀 - ‘끌어당김’이 신비한 베스트셀러는 많은 이를 보통 사람에서 성공한 사람으로 만들었다.“우리가 내면의 마음을 열고 우주를 지배하는 긍정의...", review: "", rating: 4, quotes: [] },
  { title: "각성", author: "김요한", genres: [], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791192372754.jpg", isbn: "9791192372754",
    summary: "사람은 누구도 대신 살아주지 않는다.그 단순한 사실을 받아들이기까지, 우리는 얼마나 돌아야 하는가.『각성』은 단순한 위로를 거부한다. 긍정도, 희망도, 달콤한 말도 없다. 대신 단 한 줄의 진심만 남는다.지금 이대로는 무너진다.", review: "", rating: 3, quotes: [] },
  { title: "다크 심리학", author: "다크 사이드 프로젝트", genres: ["심리"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791198754080.jpg", isbn: "9791198754080",
    summary: "국내 최초 ‘다크 심리학’을 기반한 심리 기술출간 전부터 50만 팔로워가 기다린 바로 그 책!지금, 당신이 살아남기 위해 꼭 읽어야 『다크 심리학』‘다크 심리학’은 인간 본성의 어두운 면을 탐구하여 타인의 감정을 조종하거나 조작하는 기술을 융합한 것이다.", review: "", rating: 3, quotes: [] },
  { title: "돈이 자유다", author: "얼음공장", genres: ["재테크"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788960306516.jpg", isbn: "9788960306516",
    summary: "“가난은 죄가 아니지만, 방관은 죄다”부는 ‘나의 성장’이 아니라 ‘자산의 가치’에서 시작된다집값이 떨어질 땐 겁이 나서 움직이지 못하고, 조금 오르기 시작하면 이미 대출은 꽉 막혀 있다. 기회를 잡으려는 순간마다 새로운 규칙이 생기고, 우리는 늘 한발 늦는다...", review: "", rating: 3, quotes: [] },
  { title: "100세 할머니 약국", author: "히루마 에이코", genres: ["소설"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791199247833.jpg", isbn: "9791199247833",
    summary: "세대를 건너 마음속 깊이 새겨지는 문장들흰 가운을 입고, 매일 같은 자리에 앉아 손님을 맞는 백세의 약사. 그녀는 약보다 먼저 사람의 얼굴을 살핀다. “오늘 기운이...", review: "", rating: 3, quotes: [] },
  { title: "너라는 브랜드를 마케팅하라", author: "이소라", genres: ["마케팅", "자기계발"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791193941393.jpg", isbn: "9791193941393",
    summary: "연봉 40만 달러 META, TikTok 전략 임원 출신셀프 브랜딩이 중요해진 시대, 직장 생활도 마찬가지다!‘존재감’ 있게 일하고 ‘성공적’인 인생을 설계하는 힘...", review: "", rating: 2, quotes: [] },
  { title: "인생을 바꾸는 이메일 쓰기", author: "이슬아", genres: ["에세이", "글쓰기"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791194184331.jpg", isbn: "9791194184331",
    summary: "전설의 귀환 「일간 이슬아」의 영업비밀 공개!“이메일로 팔자 고친다는 말이 과장처럼 들리는가?” 이메일로 천냥 빚을 갚고,한국문학의 판도를 이메일로 바꿔버린이슬아 작가가 직접 풀어놓는 섭외와 조율, 설득의 비법여기 제도권의 그 어떤 청탁도, 초대도 없이 오직 ...", review: "", rating: 5, quotes: [] },
  { title: "월스트리트저널 인포그래픽 가이드", author: "도나 M. 웡", genres: ["디자인"], published: 2014, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788966260935.jpg", isbn: "9788966260935",
    summary: "에드워드 터프티(Edward Tufte)의 이론과 다양한 실무 사례로 녹여낸 데이터 시각화 핵심 가이드. 데이터 시각화를 똑똑하게 보여주는 차트 작성의 기본 원칙: 해야 할 것 vs. 하지 말아야 할 것, 풍부한 콘텐츠를 흡인력 있는 시각화로 정교하게 구현하는...", review: "", rating: 5, quotes: [] },
  { title: "나는 이불 속에서 콘텐츠로 월급 번다", author: "보스언니(조경진)", genres: ["자기계발"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791162544235.jpg", isbn: "9791162544235",
    summary: "“나는 콘텐츠 하나로 경제적 자유를 샀다!”평범한 주부가 억대 연봉을 만들 수 있었던 콘텐츠 비즈니스 노하우!‘돈 주고 모닝콜을 구매하는 사람도 있나요?’ ‘트레이너도 아닌데 스쾃 100개 챌린지를 함께 할까요?’ 물론이다.", review: "", rating: 2, quotes: [] },
  { title: "언와인드: 하비스트 캠프의 도망자", author: "닐 셔스터먼", genres: ["소설", "SF"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788932925226.jpg", isbn: "9788932925226",
    summary: "전 세계 문학상 15종 수상, 추천 도서 선정 다수전미 도서상 수상 작가이자 전작 「수확자」 시리즈로 한국 독자의 큰 사랑을 받은 닐 셔스터먼의 대표적 SF 「언와인드 디스톨로지」 시리즈가 강동혁 번역가의 ...", review: "", rating: 4, quotes: [] },
  { title: "워런 버핏 삶의 원칙", author: "구와바라 데루야", genres: ["투자"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791193262641.jpg", isbn: "9791193262641",
    summary: "빌 게이츠, 찰리 멍거, 벤저민 그레이엄 등 거장들과의 일화 수록버핏의 삶은 엄격한 원칙 위에서 완성됐다.투자에서도, 인생에서도 그의 성공을 따르고 싶다면 삶의 방식부터 훔쳐야 한다...", review: "", rating: 2, quotes: [] },
  { title: "누구도 대신 살아 주지 않는다", author: "브라이언 트레이시", genres: ["자기계발"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791173740701.jpg", isbn: "9791173740701",
    summary: "평범함에 좌절하지 말라, 당신도 할 수 있다누구도 대체 불가능한 성공의 주인공으로 이끌브라이언 트레이시의 마스터 클래스흙수저 고교 중퇴자에서 자수성가의 아이콘으로500만 명의 운명을 뒤바꾼 명강의 최신판당신의 새로운 미래를 보증하는 성공의 백지수표자수성가의 아...", review: "", rating: 5, quotes: [] },
  { title: "자몽살구클럽", author: "한로로", genres: ["소설"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791199305304.jpg", isbn: "9791199305304",
    summary: "『자몽살구클럽』은 싱어송라이터 한로로가 발매할 세 번째 EP 음악 앨범과 연결된 동명의 소설이다. 그는 데뷔 싱글 `입춘`부터 지금까지 사회의 그림자 속에서 살아가는 청춘의 이야기를 음악으로 만들어오고 있다. 이는 한로로 자신이 대한민국 사회 속에서 버둥거리며...", review: "", rating: 3, quotes: [] },
  { title: "보도 섀퍼의 돈", author: "보도 섀퍼", genres: ["재테크"], published: 2011, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788919205013.jpg", isbn: "9788919205013",
    summary: "재테크의 기본 개념을 갖게 해주는 책경제를 넘어 인생까지 폭넓게 생각하게 하는 책부자가 되는 것은 결코 기적이 아니다!돈을 버는데 비상한 재능이 있는 이 책의 저자 보도 섀퍼는 열여섯에 독일에서 미국으로 건너가 고등학교를 졸업하고, 독일과 멕시코에서 법학을 전...", review: "", rating: 5, quotes: [] },
  { title: "액스", author: "도널드 웨스트레이크", genres: ["소설", "스릴러"], published: 2025, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791192385365.jpg", isbn: "9791192385365",
    summary: "“『액스』를 영화로 만드는 것은 제 필생의 프로젝트입니다.”“어떤 이론서보다 자본주의 체제에서의 노동자의 처지를 정확하게 묘사한 이 소설을 무릇 월급쟁이라면 다 읽어야 한다고 나는 생각합니다.”_박찬욱 에드거 상 3회 수상에 빛나는 추리소설의 대가 도널드 E....", review: "", rating: 5, quotes: [] },
  { title: "트라이브즈", author: "세스 고딘", genres: ["경제경영", "마케팅"], published: 2026, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791193262993.jpg", isbn: "9791193262993",
    summary: "“세상을 바꾸는 힘, 트라이브즈“세계적인 마케팅 전략가 세스 고딘의 또 다른 예언서!누구도 대신할 수 없는 대체 불가능한 조직의 조건초개인화 사회, 나의 가치를 극대화할 최적의 조직과 연결하라!", review: "", rating: 4, quotes: [] },
  { title: "더 기버 1", author: "밥 버그·존 데이비드 만", genres: ["자기계발"], published: 2026, readYear: null,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791175771963.jpg", isbn: "9791175771963",
    summary: "애덤 그랜트, 세스 고딘, 브라이언 트레이시 강력 추천“베푸는 자에게는 거대한 성공이 알아서 찾아온다!”가치, 보상, 영향력, 진정성, 수용...", review: "", rating: 5, quotes: [] },
  // ===== 2026년 기록 =====
  { title: "강수의 괴이도감", author: "현찬양", genres: [], published: 2026, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791175910997.jpg", isbn: "9791175910997",
    summary: "허약한 소공자와 엉터리 맹인 점복사의 괴이 탐사 여행!《잠 못 드는 궁궐 기담》 현찬양 신작 오컬트 역사 판타지《잠 못 드는 궁궐 기담》 《식탐정 허균》 등 역사 판타지 페이지터너로 활약해온 이야기꾼 현찬양의 신작 장편소설 《강수의 괴이도감》이 위즈덤하우스에서...", review: "", rating: 3, quotes: [] },
  { title: "웨딩피플", author: "앨리슨 에스파흐", genres: [], published: 2026, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791124038437.jpg", isbn: "9791124038437",
    summary: "* 《뉴욕타임스》 종합 베스트셀러* `굿리즈 초이스 어워드` 소설 1위* 《가디언》 《타임》 《시카고 트리뷴》 `올해의 책`* 《피플》 `여름 최고의 도서` 선정* 미국 전역 서점원 투표 `인디 넥스트 픽` 1위* 100만 부 밀리언셀러 돌파 · 소니 픽처스 ...", review: "", rating: 3, quotes: [] },
  { title: "서울의 선인", author: "김호연", genres: [], published: 2026, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791175910942.jpg", isbn: "9791175910942",
    summary: "180만 부 판매 신화 『불편한 편의점』 김호연 작가의 신작 장편소설!어느 날 당신 앞에 도시의 멸망을 예고하는 천사가 나타난다면?도시의 운명을 두고 펼쳐지는 강력한 휴먼드라마국내 180만 부 판매, 전 세계 50여 개국에 수출된 『불편한 편의점』 김호연 작가...", review: "", rating: 3, quotes: [] },
  { title: "일요일에 잊힌 사람들", author: "발레리 페랭", genres: ["소설"], published: 2015, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791191247749.jpg", isbn: "9791191247749",
    summary: "요양원에서 일하는 쥐스틴이 노인들의 잊힌 삶과 감춰진 비밀을 마주하며 자신의 과거와도 화해해 가는 이야기.",
    review: "", rating: 5, quotes: [] },
  { title: "세상 대신 샌드백을 때리기로 했습니다", author: "윤리", genres: ["에세이"], published: 2026, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791124370483.jpg", isbn: "9791124370483",
    summary: "남들과 자신을 끊임없이 비교하며 지쳐가는 시대. 『세상 대신 샌드백을 때리기로 했습니다』는 타인의 기준에 맞추기 위해 애쓰다 결국 스스로를 잃어버린 사람들에게 건네는 다정한 위로이자, 다시 일어설 수 있는 용기에 대한 이야기다.저자는 복싱이라는 운동을 통해 삶...", review: "", rating: 1, quotes: [] },
  { title: "유혹하는 글쓰기", author: "스티븐 킹", genres: ["글쓰기", "에세이"], published: 2000, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791173324901.jpg", isbn: "9791173324901",
    summary: "스티븐 킹이 자신의 삶과 창작 과정을 솔직하게 풀어낸 글쓰기 지침서.",
    review: "", rating: 5, quotes: [] },
  { title: "스페이스X 일론머스크", author: "에릭 버거", genres: ["경제경영"], published: 2026, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791124248270.jpg", isbn: "9791124248270",
    summary: "“인류의 역사 기록에 반드시 추가해야 할 책!”_앤디 랩사, 스토크스페이스 CEO퓰리처상 최종 후보자 에릭 버거의 최신작전미 인디 엑설런스 어워드 기술 부문 수상작 ⟨이코노미스트⟩ 선정 최고의 책, ⟨USA 투데이⟩ 베스트셀러기술, 광기, 야망이 이룩한 우주 ...", review: "", rating: 3, quotes: [] },
  { title: "우리는 가장 밝은 밤에 헤어졌다", author: "표도르 도스토예프스키", genres: [], published: 2026, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791199757684.jpg", isbn: "9791199757684",
    summary: "대문호 도스토옙스키가 26세에 쓴, 가장 투명하고 순수한 연가!`영원하지 않아도 좋았다, 당신과 함께 숨 쉬던 그 찰나의 눈부심이라면…….`가장 밝은 밤에 ...", review: "", rating: 3, quotes: [] },
  { title: "쓰레기섬", author: "표창원", genres: [], published: 2026, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791124028681.jpg", isbn: "9791124028681",
    summary: "소설가 표창원, 더 치밀하고 거대해진 세계관의 귀환! 도심 한복판, 열 개의 잘린 손가락이 남긴 잔혹한 경고. ‘표현의 자유’라는 방패 뒤에 숨은 영혼의 도살자들, ‘말’과 ‘글’의 쓰레기를 생산하는 원흉들을 향한 피의 심판이 시작된다.", review: "", rating: 1, quotes: [] },
  { title: "경제사상가 이건희 1: 생각", author: "허문명", genres: ["경제경영"], published: 2026, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791192101453.jpg", isbn: "9791192101453",
    summary: "“반도체 패권 시대가 온다.”“자동차는 바퀴 달린 컴퓨터가 된다.”“로봇이 인간의 노동을 대신하는 시대가 온다. 그때는 인간의 창의성이 더 중요해질 것이다.”30여 년 전, 이건희 회장은 이렇게 말했다. 그의 ‘예언’은 모두 현실이 됐다.", review: "", rating: 5, quotes: [] },
  { title: "죽은 자의 스토킹", author: "알렉스 안도릴", genres: [], published: 2026, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791124468197.jpg", isbn: "9791124468197",
    summary: "추리물 열풍을 일으킨 베스트셀러 『아이가 없는 집』 후속작“죽은 약혼자가 돌아왔다… 도대체 왜?”끝까지 모든 것을 의심하게 만드는 전율의 트릭!‘율리아 스타르크 시리즈’ 두 번째 이야기 『죽은 자의 스토킹』더...", review: "", rating: 4, quotes: [] },
  { title: "더 티처", author: "프리다 맥파든", genres: [], published: 2026, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791170965817.jpg", isbn: "9791170965817",
    summary: "《뉴욕타임스》 베스트셀러 17주 연속 1위애플 오리지널 필름스 시리즈 제작 확정전 세계 46개 언어로 5,500만 부 판매, 5개 대륙 14개국 베스트셀러 1위이제, 프리다 맥파든의 시간이다!출간하는 책마다 전 세계 베스트셀러에 오르는 경이로운 기록을 써나가고...", review: "", rating: 3, quotes: [] },
  { title: "이혼", author: "프리다 맥파든", genres: [], published: 2026, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791193324967.jpg", isbn: "9791193324967",
    summary: "프리다 맥파든 최신작최초 한미 동시 출간!“당신은 절대 나랑 이혼 못 해.”상상 초월 부부의 피 튀기는 이혼이 시작됐다!내가 돈 많은 연하 남편과 결혼할 수 있었던 건 단지 아이가 생겼기 때문이었다. 하지만 결혼 생활은 나쁘지 않았다.", review: "", rating: 4, quotes: [] },
  { title: "어느 멋진 도망", author: "나상천", genres: [], published: 2026, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791169087223.jpg", isbn: "9791169087223",
    summary: "누군가가 곁에서 나란히 걸어준다는 것만으로도 인생은 달라질지 모른다한 걸음씩 내디딜 때마다 홀가분해지는 33일의 순례길 여정극작가 출신 케이팝 기획자 나상천이 선사하는 힐링 드라마밀리의서재 연재 최단기간 최다 ‘밀어주리’ 달성시인 원태연, ‘시든 꽃에 물을 주...", review: "", rating: 2, quotes: [] },
  { title: "AI 최전선", author: "애덤 브로트먼", genres: ["과학기술"], published: 2026, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791155818961.jpg", isbn: "9791155818961",
    summary: "급변하는 AX 시대에 발맞춰 가기 위한 실리콘밸리 구루들의 명쾌하고 실천적인 해답. 『AI 최전선』은 시장을 지배하는 5%와 도태되는 95% 기업의 결정적 차이를 낱낱이 파헤치는 책이다. “AI가 일의 95%를 대체할 것이다.” 샘 올트먼의 섬뜩한 예언 앞에 ...", review: "", rating: 1, quotes: [] },
  { title: "내면 근력", author: "짐 머피", genres: ["자기계발"], published: 2026, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791155819227.jpg", isbn: "9791155819227",
    summary: "전 세계 27개국 번역 출간! 75만 독자가 열광한 초대형 베스트셀러", review: "", rating: 3, quotes: [] },
  { title: "비범한 평범", author: "조수용", genres: [], published: 2025, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791193383285.jpg", isbn: "9791193383285",
    summary: "‘브랜드란 평범한 아이디어를 구체적인 현실로 만들어가는 비범한 과정의 결과물이다’매거진《B》 발행인 조수용의 본격 브랜드 이야기매거진《B》의 발행인 조수용의 신간 《비범한 평범》이 출간되었다. 작년에 출간된 첫 단독 에세이 《일의 감각》에서 디자인과 크리에이티...", review: "", rating: 3, quotes: [] },
  { title: "일본 광고 카피 도감", author: "오하림", genres: ["광고", "글쓰기"], published: 2026, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791199555112.jpg", isbn: "9791199555112",
    summary: "마음에 시동을 거는 `여행` 카피 특별부록TBWA에서 오랜 카피라이터 시절을 보내고 무신사를 거쳐 29CM에서 헤드 카피라이터로 ...", review: "", rating: 3, quotes: [] },
  { title: "열두살에 부자가된 키라", author: "보도 섀퍼", genres: ["경제경영", "자기계발"], published: 2025, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791173470905.jpg", isbn: "9791173470905",
    summary: "소녀 키라가 말하는 개 '머니'를 만나 돈과 저축, 목표 세우기를 배우며 성장하는 어린이 경제 동화.",
    review: "", rating: 5, quotes: [] },
  { title: "결국 너의 시간은 온다", author: "염경엽", genres: ["자기계발"], published: 2025, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788901298757.jpg", isbn: "9788901298757",
    summary: "LG 트윈스 최초 두 번의 통합우승 달성!왕조의 시작, 명장의 탄생을 알리는 뜨거운 승리 너머의 이야기실패한 1할 타자에서 최고의 감독이 되기까지,끝끝내 자신을 증명해온 감독 염경엽의 시간선수·단장·감독으로서 모두 우승을 경험한 KBO 최초의 인물이자, 프로야...", review: "", rating: 3, quotes: [] },
  { title: "당신의 가능성에 대하여", author: "벤저민 잰더", genres: ["자기계발"], published: 2025, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791169851633.jpg", isbn: "9791169851633",
    summary: "“남은 생에 한 권의 책만 읽을 수 있다면난 무조건 이 책을 읽겠다” _세스 고딘17개국 100만 부 판매! 23년간 베스트셀러!팀 페리스, 세스 고딘, 제임스 클리어가 추천한 불멸의 자기계발서팀 페리스, 세스 고딘, 제임스 클리어…… 자기계발 분야에서 거장이...", review: "", rating: 5, quotes: [] },
  { title: "마일리지 아워", author: "최유나", genres: [], published: 2025, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791124038093.jpg", isbn: "9791124038093",
    summary: "“시간을 다르게 쓰는 사람이 결국 다르게 산다”나만의 속도로 쌓은 시간이 삶을 변화시키는 순간희대의 미스터리 : 한 사람이 법무법인 대표 변호사, 작가, 아들 둘 워킹맘, 인스타툰 작가, 「굿파트너」 드라마 작가라고?", review: "", rating: 3, quotes: [] },
  { title: "팔리는 글은 처음이라", author: "제갈현열", genres: ["글쓰기", "마케팅"], published: 2025, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791130666242.jpg", isbn: "9791130666242",
    summary: "40만부 판매 베스트셀러 저자, 마케팅 기획자, 경영 컨설턴트, 콘텐츠 기획자모든 영역의 글쓰기를 다루는 제갈현열이 전하는 ‘팔리는 글쓰기’의 모든 것", review: "", rating: 3, quotes: [] },
  { title: "퇴사 후 나를 브랜딩합니다", author: "커밍쏜", genres: ["자기계발"], published: 2025, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788925573021.jpg", isbn: "9788925573021",
    summary: "주언규, 한석준… 수많은 1인 기업가들의 극찬!1인 크리에이터들이 인생 멘토로 꼽는 커밍쏜의 첫 책이 출간되었다. 스스로를 브랜딩하지 않으면 살아남기 힘든 시대, 커밍쏜은 ‘퍼스널 브랜딩’으로 인생을 바꾼 인물이다....", review: "", rating: 3, quotes: [] },
  { title: "솔직히 말할게요 저는 돈이 좋아요", author: "디노더노마드(이지영)", genres: ["재테크"], published: 2025, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791194600718.jpg", isbn: "9791194600718",
    summary: "170만 원 월급을 받던 인천공항 세관 공무원. 안정적인 직장이었지만, 그녀의 마음속에는 ‘이대로 평생 살아도 될까?’라는 불안이 매일같이 맴돌았다. 답답한 현실에서 벗어나고자 ‘부업’이라는 단어를 검색한 순간, 인생은 다른 궤도로 움직이기 시작했다.", review: "", rating: 3, quotes: [] },
  { title: "회사 없는 세계에서 살아남기", author: "부아c", genres: ["자기계발"], published: 2025, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788968335143.jpg", isbn: "9788968335143",
    summary: "회사라는 울타리를 벗어나 흔들림 없이 사는 법에 대하여회사 없는 세계에서 무너질 것인가, 살아남을 것인가?지금 당장 회사 밖 인생을 준비하라!많은 사람들이 은퇴를 먼 미래의 일로 여긴다. 그러나 현실은 다르다. 은퇴는 우리가 예상하는 것보다", review: "", rating: 2, quotes: [] },
  { title: "직장인입니다 강남으로 이사 갔고요 질문 받습니다", author: "대치대디", genres: [], published: 2025, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791169851541.jpg", isbn: "9791169851541",
    summary: "“낄낄 웃으며 봤는데,나도 모르게 부동산을 보는 제3의 눈이 떠졌다!”여섯 살 딸과 맞벌이 부부의 좌충우돌 생애 첫 집 갈아타기 이야기. 딸의 초등학교 입학을 앞두고, 부부는 처음으로 부동산 매수·매도에 도전한다. 한 번도 부동산에 들어가 본 적 없던 저자가 ...", review: "", rating: 2, quotes: [] },
  { title: "피안장의 유령", author: "아야사카 미쓰키", genres: [], published: 2025, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788925573090.jpg", isbn: "9788925573090",
    summary: "불의의 죽음을 맞거나 행방불명된다는 흉한 곳,과연 실제로도 존재할까? 저주가 깃든 공간을 밀실로 삼아 그곳에서 일어난 살인사건의 전모를 파헤치는 것은 미스터리에 단골로 등장하는 소재다. 대학 미스터리 동호회에서 습작을 거쳐 초단편 미스터리로 데뷔한 아야사카 미...", review: "", rating: 4, quotes: [] },
  { title: "부자는 왜 더 부자가 되는가", author: "로버트 기요사키", genres: ["재테크", "경제경영"], published: 2017, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791170525516.jpg", isbn: "9791170525516",
    summary: "왜 금융 지식이 있는 사람에게 부가 몰리는지를 세금·부채·자산의 관점에서 설명하는 재테크서.",
    review: "", rating: 4, quotes: [] },
  { title: "나는 4시간만 일한다", author: "팀 페리스", genres: ["자기계발", "경제경영"], published: 2007, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791185584454.jpg", isbn: "9791185584454",
    summary: "적게 일하고도 시간과 돈의 자유를 얻는 삶을 설계하는 방법을 제안하는 자기계발서.",
    review: "", rating: 3, quotes: [] },
  { title: "부자의 언어", author: "존 소포릭", genres: ["재테크"], published: 2023, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791155815915.jpg", isbn: "9791155815915",
    summary: "아버지가 아들에게 물려주고 싶은 ‘부의 말들’진짜 부를 향한 인생 수업이 시작된다!출간 즉시 경제 경영 분야 베스트셀러에 오르고, 현재까지 수많은 독자에게 ‘인생 책’으로 꼽히는 『부자의...", review: "", rating: 3, quotes: [] },
  { title: "저소비 생활", author: "가제노타미", genres: ["재테크"], published: 2025, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788925573229.jpg", isbn: "9788925573229",
    summary: "“내 삶에 만족하면 돈 쓸 일이 줄어든다”월 70만 원, 불필요한 지출을 줄이고 필요한 것에 집중하기 ◆ 총 조회 수 2,400만 화제의 절약법 ◆ 아마존 재팬 베스트셀러◆ 뉴 소비 트렌드 ‘안티 플렉스’, ‘요노’ 실전편 ◆ 김경필, 곽지현(자취린이) 강력 ...", review: "", rating: 2, quotes: [] },
  { title: "왜 나는 너를 사랑하는가", author: "알랭 드 보통", genres: ["소설", "에세이"], published: 1993, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788986836837.jpg", isbn: "9788986836837",
    summary: "한 연애의 시작부터 끝까지를 철학적 시선으로 세밀하게 해부한 알랭 드 보통의 연애 소설.",
    review: "", rating: 2, quotes: [] },
  { title: "부자 아빠 가난한 아빠", author: "로버트 기요사키", genres: ["재테크", "경제경영"], published: 1997, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791158883591.jpg", isbn: "9791158883591",
    summary: "두 아버지의 상반된 돈에 대한 태도를 통해 자산과 부채, 금융 지능의 차이를 이야기하는 재테크 고전.",
    review: "", rating: 5, quotes: [] },
  { title: "행복 강박", author: "올리버 버크먼", genres: [], published: 2025, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791193937778.jpg", isbn: "9791193937778",
    summary: "행복 만능주의에 대한 괴상하지만 냉철한 반격“행복해지려고 하지 마라! 그 생각이 당신을 불행하게 할 것이다”", review: "", rating: 2, quotes: [] },
  { title: "강하고 아름다운 할머니가 되고 싶어", author: "김슬기", genres: ["에세이"], published: 2025, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791193235607.jpg", isbn: "9791193235607",
    summary: "제12회 브런치북 출판 프로젝트 대상소설 부문 최초 수상작고수리 작가 · 황예인 문학평론가 추천“다 자란 어른이 회복하는 데도 온 마을이 필요하다”몸은 자랐지만 마음은 아직 다 자라지 못한 지친 어른을 구하러 온, 진짜 강하고 아름다운 어른들!", review: "", rating: 3, quotes: [] },
  { title: "달러 자산 1억으로 평생 월급 완성하라", author: "채부심(채상욱)", genres: ["재테크", "투자"], published: 2025, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791199229976.jpg", isbn: "9791199229976",
    summary: "부록 1. 이재명 시대, 자산시장 대전환 실전 가이드북부록 2. 지금 사야 할 주식 - ETF 비공개 강의 이 책은 단기 수...", review: "", rating: 3, quotes: [] },
  { title: "주식 투자의 기쁨", author: "후지모토 시게루", genres: ["재테크", "투자"], published: 2025, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791130668895.jpg", isbn: "9791130668895",
    summary: "“주식도 인생도, 숱한 굴곡을 버텨내는 자가 승리합니다.”70년간 폭등장과 폭락장을 겪으며 180억의 자...", review: "", rating: 3, quotes: [] },
  { title: "넷플릭스처럼 쓴다", author: "낸시 크레스 외", genres: ["글쓰기"], published: 2020, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791156333012.jpg", isbn: "9791156333012",
    summary: "매력적인 세계관 설정에서 팬덤을 모으는 캐릭터 창조까지성공한 작가들의 66가지 노하우와 실전연습!넷플릭스는 어떤 작품에 끌릴까? 드라마 · 영화 · 게임 제작자들에게 검증받은 할리우드 최고의 작가 66명이 명쾌한 4가지 기준을 제시한다.", review: "", rating: null, quotes: [] },
  { title: "댈러웨이 부인", author: "버지니아 울프", genres: ["소설", "고전"], published: 1925, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788937464843.jpg", isbn: "9788937464843",
    summary: "1차 대전 후 런던의 어느 하루, 파티를 준비하는 클라리사 댈러웨이의 하루를 의식의 흐름으로 따라가는 모더니즘 걸작.",
    review: "", rating: null, quotes: [] },
  { title: "설득", author: "제인 오스틴", genres: ["소설", "고전"], published: 1817, readYear: 2026,
    cover: "https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788937463488.jpg", isbn: "9788937463488",
    summary: "집안의 설득으로 파혼했던 앤 엘리엇이 8년 만에 웬트워스 대령과 재회하며 다시 사랑을 확인해 가는 제인 오스틴의 마지막 소설.",
    review: "둘째들은 더욱 공감할 것. 명불허전 로맨스.", rating: 4, quotes: [] },
  { title: "여름", author: "이디스 워튼", genres: [], published: 2026, readYear: 2026,
    cover: "", isbn: "",
    summary: "", review: "", rating: null, quotes: [] },
];
