// ============================================================
//  나의 독서 데이터
//  - 이 파일이 "원본"입니다. 화면(index.html)의 "+ 책 추가" 버튼으로
//    넣은 책은 브라우저에만 저장되니, 영구 보관하려면 그 책들을
//    "내보내기"로 복사해 아래 배열에 붙여넣으세요.
//
//  ※ 아래 2026년 목록은 제목/별점/읽은 해만 확정값입니다.
//     author · genres · published · summary 는 제가 '확실히 아는 책'만
//     채웠고, 모르는 항목은 빈칸("", [], null)으로 두었습니다.
//     빈칸은 화면의 책 상세에서 '수정'하거나 이 파일에서 채우면 됩니다.
//
//  필드: title, author, genres[], published, readYear,
//        summary, review, rating(1~5), quotes[]
// ============================================================

const BOOKS = [
  { title: "강수의 괴이도감", author: "현찬양", genres: [], published: null, readYear: 2026,
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "웨딩피플", author: "앨리슨 에스파흐", genres: [], published: null, readYear: 2026,
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "서울의 선인", author: "", genres: [], published: null, readYear: 2026,
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "일요일에 잊힌 사람들", author: "발레리 페랭", genres: ["소설"], published: 2015, readYear: 2026,
    summary: "요양원에서 일하는 쥐스틴이 노인들의 잊힌 삶과 감춰진 비밀을 마주하며 자신의 과거와도 화해해 가는 이야기.",
    review: "", rating: 5, quotes: [] },
  { title: "세상 대신 샌드백을 때리기로 했습니다", author: "", genres: ["에세이"], published: null, readYear: 2026,
    summary: "", review: "", rating: 1, quotes: [] },
  { title: "유혹하는 글쓰기", author: "스티븐 킹", genres: ["글쓰기", "에세이"], published: 2000, readYear: 2026,
    summary: "스티븐 킹이 자신의 삶과 창작 과정을 솔직하게 풀어낸 글쓰기 지침서.",
    review: "", rating: 5, quotes: [] },
  { title: "스페이스X 일론머스크", author: "에릭 버거", genres: ["경제경영"], published: null, readYear: 2026,
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "우리는 가장 밝은 밤에 헤어졌다", author: "", genres: [], published: null, readYear: 2026,
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "쓰레기섬", author: "", genres: [], published: null, readYear: 2026,
    summary: "", review: "", rating: 1, quotes: [] },
  { title: "경제사상가 이건희 1: 생각", author: "허문명", genres: ["경제경영"], published: null, readYear: 2026,
    summary: "", review: "", rating: 5, quotes: [] },
  { title: "죽은 자의 스토킹", author: "알렉스 안도릴", genres: [], published: null, readYear: 2026,
    summary: "", review: "", rating: 4, quotes: [] },
  { title: "더 티처", author: "", genres: [], published: null, readYear: 2026,
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "이혼", author: "", genres: [], published: null, readYear: 2026,
    summary: "", review: "", rating: 4, quotes: [] },
  { title: "어느 멋진 도망", author: "", genres: [], published: null, readYear: 2026,
    summary: "", review: "", rating: 2, quotes: [] },
  { title: "AI 최전선", author: "", genres: ["과학기술"], published: null, readYear: 2026,
    summary: "", review: "", rating: 1, quotes: [] },
  { title: "내면 근력", author: "", genres: ["자기계발"], published: null, readYear: 2026,
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "비범한 평범", author: "", genres: [], published: null, readYear: 2026,
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "일본 광고 카피 도감", author: "", genres: ["광고", "글쓰기"], published: null, readYear: 2026,
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "열두살에 부자가된 키라", author: "보도 섀퍼", genres: ["경제경영", "자기계발"], published: null, readYear: 2026,
    summary: "소녀 키라가 말하는 개 '머니'를 만나 돈과 저축, 목표 세우기를 배우며 성장하는 어린이 경제 동화.",
    review: "", rating: 5, quotes: [] },
  { title: "결국 너의 시간은 온다", author: "", genres: ["자기계발"], published: null, readYear: 2026,
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "당신의 가능성에 대하여", author: "", genres: ["자기계발"], published: null, readYear: 2026,
    summary: "", review: "", rating: 5, quotes: [] },
  { title: "마일리지 아워", author: "", genres: [], published: null, readYear: 2026,
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "팔리는 글은 처음이라", author: "", genres: ["글쓰기", "마케팅"], published: null, readYear: 2026,
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "퇴사 후 나를 브랜딩합니다", author: "", genres: ["자기계발"], published: null, readYear: 2026,
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "솔직히 말할게요 저는 돈이 좋아요", author: "", genres: ["재테크"], published: null, readYear: 2026,
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "회사 없는 세계에서 살아남기", author: "", genres: ["자기계발"], published: null, readYear: 2026,
    summary: "", review: "", rating: 2, quotes: [] },
  { title: "직장입니다 강남으로 이사갔고요 질문 받습니다", author: "", genres: [], published: null, readYear: 2026,
    summary: "", review: "", rating: 2, quotes: [] },
  { title: "피안장의 유령", author: "", genres: [], published: null, readYear: 2026,
    summary: "", review: "", rating: 4, quotes: [] },
  { title: "부자는 왜 더 부자가 되는가", author: "로버트 기요사키", genres: ["재테크", "경제경영"], published: 2017, readYear: 2026,
    summary: "왜 금융 지식이 있는 사람에게 부가 몰리는지를 세금·부채·자산의 관점에서 설명하는 재테크서.",
    review: "", rating: 4, quotes: [] },
  { title: "나는 4시간만 일한다", author: "팀 페리스", genres: ["자기계발", "경제경영"], published: 2007, readYear: 2026,
    summary: "적게 일하고도 시간과 돈의 자유를 얻는 삶을 설계하는 방법을 제안하는 자기계발서.",
    review: "", rating: 3, quotes: [] },
  { title: "부자의 언어", author: "", genres: ["재테크"], published: null, readYear: 2026,
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "저소비 생활", author: "", genres: ["재테크"], published: null, readYear: 2026,
    summary: "", review: "", rating: 2, quotes: [] },
  { title: "왜 나는 너를 사랑하는가", author: "알랭 드 보통", genres: ["소설", "에세이"], published: 1993, readYear: 2026,
    summary: "한 연애의 시작부터 끝까지를 철학적 시선으로 세밀하게 해부한 알랭 드 보통의 연애 소설.",
    review: "", rating: 2, quotes: [] },
  { title: "부자 아빠 가난한 아빠", author: "로버트 기요사키", genres: ["재테크", "경제경영"], published: 1997, readYear: 2026,
    summary: "두 아버지의 상반된 돈에 대한 태도를 통해 자산과 부채, 금융 지능의 차이를 이야기하는 재테크 고전.",
    review: "", rating: 5, quotes: [] },
  { title: "행복 강박", author: "", genres: [], published: null, readYear: 2026,
    summary: "", review: "", rating: 2, quotes: [] },
  { title: "강하고 아름다운 할머니가 되고 싶어", author: "", genres: ["에세이"], published: null, readYear: 2026,
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "달러 자산 1억으로 평생 월급 완성하라", author: "", genres: ["재테크", "투자"], published: null, readYear: 2026,
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "주식 투자의 기쁨", author: "", genres: ["재테크", "투자"], published: null, readYear: 2026,
    summary: "", review: "", rating: 3, quotes: [] },
  { title: "넷플릭스처럼 쓴다", author: "낸시 크레스 외", genres: ["글쓰기"], published: null, readYear: 2026,
    summary: "", review: "", rating: null, quotes: [] },
  { title: "댈러웨이 부인", author: "버지니아 울프", genres: ["소설", "고전"], published: 1925, readYear: 2026,
    summary: "1차 대전 후 런던의 어느 하루, 파티를 준비하는 클라리사 댈러웨이의 하루를 의식의 흐름으로 따라가는 모더니즘 걸작.",
    review: "", rating: null, quotes: [] },
  { title: "설득", author: "제인 오스틴", genres: ["소설", "고전"], published: 1817, readYear: 2026,
    summary: "집안의 설득으로 파혼했던 앤 엘리엇이 8년 만에 웬트워스 대령과 재회하며 다시 사랑을 확인해 가는 제인 오스틴의 마지막 소설.",
    review: "", rating: null, quotes: [] },
];
